// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model


// Area 省份地区表
type Area struct {
	ID        int32  `gorm:"column:id;type:int(11) unsigned;not null;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Pid       int32  `gorm:"column:pid;type:int(11) unsigned;not null;index:pid;comment:父id" json:"pid"`                            // 父id
	Shortname string `gorm:"column:shortname;type:varchar(100) default null;comment:简称" json:"shortname"`                 // 简称
	Name      string `gorm:"column:name;type:varchar(100) default null;comment:名称" json:"name"`                           // 名称
	Mergename string `gorm:"column:mergename;type:varchar(255) default null;comment:全称" json:"mergename"`                 // 全称
	Level     int32  `gorm:"column:level;type:tinyint(4) unsigned;comment:层级:1=省,2=市,3=区/县" json:"level"`           // 层级:1=省,2=市,3=区/县
	Pinyin    string `gorm:"column:pinyin;type:varchar(100) default null;comment:拼音" json:"pinyin"`                       // 拼音
	Code      string `gorm:"column:code;type:varchar(100) default null;comment:长途区号" json:"code"`                         // 长途区号
	Zip       string `gorm:"column:zip;type:varchar(100) default null;comment:邮编" json:"zip"`                             // 邮编
	First     string `gorm:"column:first;type:varchar(50) default null;comment:首字母" json:"first"`                        // 首字母
	Lng       string `gorm:"column:lng;type:varchar(50) default null;comment:经度" json:"lng"`                             // 经度
	Lat       string `gorm:"column:lat;type:varchar(50) default null;comment:纬度" json:"lat"`                             // 纬度
}

