// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

// AdminHierarchyLock 管理员层级操作互斥锁表
type AdminHierarchyLock struct {
	ID uint8 `gorm:"column:id;type:tinyint(3) unsigned;not null;primaryKey;comment:锁ID" json:"id"` // 锁ID
}
