// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

// AdminLog 管理员日志表
type AdminLog struct {
	ID         int32  `gorm:"column:id;type:int(11) unsigned;not null;primaryKey;autoIncrement:true;comment:ID" json:"id"`  // ID
	AdminID    int32  `gorm:"column:admin_id;type:int(11) unsigned;not null;default:0;comment:管理员ID" json:"admin_id"`     // 管理员ID
	Username   string `gorm:"column:username;type:varchar(20) default '';not null;comment:管理员用户名" json:"username"`      // 管理员用户名
	URL        string `gorm:"column:url;type:varchar(1500) default '';not null;comment:操作Url" json:"url"`                  // 操作Url
	Title      string `gorm:"column:title;type:varchar(100) default '';not null;comment:日志标题" json:"title"`               // 日志标题
	Data       string `gorm:"column:data;type:longtext;comment:请求数据" json:"data"`                                         // 请求数据
	IP         string `gorm:"column:ip;type:varchar(50) default '';not null;comment:IP" json:"ip"`                           // IP
	Useragent  string `gorm:"column:useragent;type:varchar(255) default '';not null;comment:User-Agent" json:"useragent"`    // User-Agent
	CreateTime int64  `gorm:"column:create_time;type:bigint(16) unsigned default null;comment:创建时间" json:"create_time"`   // 创建时间
}
