// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaCaptcha = "ba_captcha"

// BaCaptcha 验证码表
type BaCaptcha struct {
	Key        string `gorm:"column:key;primaryKey;comment:验证码Key" json:"key"`    // 验证码Key
	Code       string `gorm:"column:code;not null;comment:验证码(加密后)" json:"code"`  // 验证码(加密后)
	Captcha    string `gorm:"column:captcha;comment:验证码数据" json:"captcha"`        // 验证码数据
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"` // 创建时间
	ExpireTime int64  `gorm:"column:expire_time;comment:过期时间" json:"expire_time"` // 过期时间
}

// TableName BaCaptcha's table name
func (*BaCaptcha) TableName() string {
	return TableNameBaCaptcha
}
