// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model


// CrudLog CRUD记录表
type CrudLog struct {
	ID         int32  `gorm:"column:id;type:int(11) unsigned;not null;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                           // ID
	Tablename  string `gorm:"column:table_name;type:varchar(200) default '';not null;comment:数据表名" json:"table_name"`                                              // 数据表名
	Table      string `gorm:"column:table;type:text;comment:数据表数据" json:"table"`                                                                // 数据表数据
	Fields     string `gorm:"column:fields;type:text;comment:字段数据" json:"fields"`                                                               // 字段数据
	Status     string `gorm:"column:status;type:enum('delete','success','error','start');not null;default:start;comment:状态:delete=已删除,success=成功,error=失败,start=生成中" json:"status"` // 状态:delete=已删除,success=成功,error=失败,start=生成中
	CreateTime int64  `gorm:"column:create_time;type:bigint(16) unsigned default null;comment:创建时间" json:"create_time"`                                                     // 创建时间
}
