// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaCrudLog = "ba_crud_log"

// BaCrudLog CRUD记录表
type BaCrudLog struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                           // ID
	Tablename  string `gorm:"column:table_name;not null;comment:数据表名" json:"table_name"`                                              // 数据表名
	Table      string `gorm:"column:table;comment:数据表数据" json:"table"`                                                                // 数据表数据
	Fields     string `gorm:"column:fields;comment:字段数据" json:"fields"`                                                               // 字段数据
	Status     string `gorm:"column:status;not null;default:start;comment:状态:delete=已删除,success=成功,error=失败,start=生成中" json:"status"` // 状态:delete=已删除,success=成功,error=失败,start=生成中
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                                     // 创建时间
}

// TableName BaCrudLog's table name
func (*BaCrudLog) TableName() string {
	return TableNameBaCrudLog
}
