// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)


// Migration mapped from table <migrations>
type Migrations struct {
	Version       int64     `gorm:"column:version;type:bigint(20) unsigned;not null;primaryKey" json:"version"`
	MigrationName string    `gorm:"column:migration_name;type:varchar(100) default null" json:"migration_name"`
	StartTime     time.Time `gorm:"column:start_time;type:timestamp null default null" json:"start_time"`
	EndTime       time.Time `gorm:"column:end_time;type:timestamp null default null" json:"end_time"`
	Breakpoint    bool      `gorm:"column:breakpoint;type:tinyint(1);not null;default:0" json:"breakpoint"`
}

