// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)


// Migration mapped from table <migrations>
type Migration struct {
	Version       int64     `gorm:"column:version;primaryKey" json:"version"`
	MigrationName string    `gorm:"column:migration_name" json:"migration_name"`
	StartTime     time.Time `gorm:"column:start_time" json:"start_time"`
	EndTime       time.Time `gorm:"column:end_time" json:"end_time"`
	Breakpoint    bool      `gorm:"column:breakpoint;not null" json:"breakpoint"`
}

