// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model


// Token 用户Token表
type Token struct {
	Token      string `gorm:"column:token;type:varchar(70) default '';primaryKey;comment:Token" json:"token"`  // Token
	Type       string `gorm:"column:type;type:varchar(15) default '';not null;comment:类型" json:"type"`         // 类型
	UserID     int32  `gorm:"column:user_id;type:int(11) unsigned;not null;default:0;comment:用户ID" json:"user_id"` // 用户ID
	CreateTime int64  `gorm:"column:create_time;type:bigint(16) unsigned default null;comment:创建时间" json:"create_time"`  // 创建时间
	ExpireTime int64  `gorm:"column:expire_time;type:bigint(16) unsigned default null;comment:过期时间" json:"expire_time"`  // 过期时间
}


