// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model


// UserScoreLog 会员积分变动表
type UserScoreLog struct {
	ID         int32  `gorm:"column:id;type:int(11) unsigned;not null;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID     int32  `gorm:"column:user_id;type:int(11) unsigned;not null;default:0;comment:会员ID" json:"user_id"`          // 会员ID
	Score      int32  `gorm:"column:score;type:int(11) unsigned;not null;default:0;comment:变更积分" json:"score"`              // 变更积分
	Before     int32  `gorm:"column:before;type:int(11) unsigned;not null;default:0;comment:变更前积分" json:"before"`           // 变更前积分
	After      int32  `gorm:"column:after;type:int(11) unsigned;not null;default:0;comment:变更后积分" json:"after"`             // 变更后积分
	Memo       string `gorm:"column:memo;type:varchar(255) default '';not null;comment:备注" json:"memo"`                  // 备注
	CreateTime int64  `gorm:"column:create_time;type:bigint(16) unsigned default null;comment:创建时间" json:"create_time"`           // 创建时间
}
