// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model


// UserMoneyLog 会员余额变动表
type UserMoneyLog struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID     int32  `gorm:"column:user_id;not null;comment:会员ID" json:"user_id"`          // 会员ID
	Money      int32  `gorm:"column:money;not null;comment:变更余额" json:"money"`              // 变更余额
	Before     int32  `gorm:"column:before;not null;comment:变更前余额" json:"before"`           // 变更前余额
	After      int32  `gorm:"column:after;not null;comment:变更后余额" json:"after"`             // 变更后余额
	Memo       string `gorm:"column:memo;not null;comment:备注" json:"memo"`                  // 备注
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}


