// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiretest

import (
	"go-build-admin/app/pkg/data_scope"
)

// Injectors from wire.go:

// Initialize proves the application package provider graph can resolve the
// Enforcer interface required by a generated scoped model.
func Initialize() *generatedScopedModel {
	denyAllEnforcer := data_scope.NewDenyAllEnforcer()
	wiretestGeneratedScopedModel := newGeneratedScopedModel(denyAllEnforcer)
	return wiretestGeneratedScopedModel
}

// wire.go:

// generatedScopedModel mirrors the constructor shape emitted by the CRUD
// template: a scoped model receives the Enforcer explicitly.
type generatedScopedModel struct {
	Enforcer data_scope.Enforcer
}

func newGeneratedScopedModel(enforcer data_scope.Enforcer) *generatedScopedModel {
	return &generatedScopedModel{Enforcer: enforcer}
}
