app:
  env: 'local'
  port: 9989
  app_name: 'go-build-admin'
  time_zone: 'Asia/Shanghai'
  cors_request_domain:  'localhost,127.0.0.1' #允许跨域访问的域名
  admin_login_captcha: true #是否开启管理员登录验证码
  user_login_retry: 10  #会员登录失败可重试次数,false则无限
  admin_login_retry: 10 #管理员登录失败可重试次数,false则无限
  admin_sso: false #开启管理员单处登录它处失效
  user_sso: false #开启会员单处登录它处失效
  user_token_keep_time: 259200  #会员登录态保持时间（非刷新token，3天）
  admin_token_keep_time: 259200 #管理员登录态保持时间（非刷新token，3天）
  auto_sort_eq_weight: false #表格拖拽排序时,两个权重相等则自动重新整理;控制器类中也有此项（作为单控制器自定义配置）
  open_member_center: true #开启前台会员中心
  module_pure_install: true  #模块纯净安装（安装时移动模块文件而不是复制）
  auto_write_admin_log: true #自动写入管理员操作日志
  default_avatar: '/static/images/avatar.png' #缺省头像图片路径
  cdn_url: ''  #内容分发网络URL，末尾不带`/`
  version: 'v2.0.4' #版本号
  api_url': 'https://localhost:9989' #接口地址

#点选验证码配置
click_captcha: 
  #模式:text=文字,icon=图标(若只有icon则适用于国际化站点)
  mode: 'text,icon'
  #长度
  length: 2
  #混淆点长度
  confuse_length: 2

log:
  level: 'info'
  root_dir: 'storage/logs'
  filename: 'app.log'
  format: ''
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true

mysql:
  driver: 'mysql'
  host: '127.0.0.1'
  port: 3306
  database: 'buildadmin'
  username: 'root'
  password: 'root'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'
  prefix: 'ba_'

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 86400
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800

token:
  default: 'mysql'
  key: 'tcbDgmqLVzuAdNH39o0QnhOisvSCFZ7I'
  algo: 'sha256'

redis:
  host: '192.168.56.105'
  port: 6379
  db: 5
  password: ''

upload:
  maxsize: 10485760 #单位byte
  savename: '/storage/{topic}/{year}{mon}{day}/{filename}{filesha1}{.suffix}'
  mimetype: 'jpg,png,bmp,jpeg,gif,webp,zip,rar,xls,xlsx,doc,docx,wav,mp4,mp3,txt'
  mode: 'local'


terminal:
  npm_package_manager: 'npm'
  install_service_port: '8000'
  commands:
    migrate:
      run: 
        cwd: ''
        command: 'php think migrate:run'
      rollback: 
        cwd: ''
        command: 'php think migrate:rollback'
      breakpoint: 
        cwd: ''
        command: 'php think migrate:breakpoint'
    install:
      yarn: 
        cwd: ''
        command: 'npm install -g yarn'
      pnpm: 
        cwd: ''
        command: 'npm install -g pnpm'
      ni: 
        cwd: ''
        command: 'npm install -g @antfu/ni'
    version:
      npm:
        cwd: ''
        command: 'npm -v'
      cnpm: 
        cwd: ''
        command: 'cnpm -v'
      yarn: 
        cwd: ''
        command: 'yarn -v'
      pnpm: 
        cwd: ''
        command: 'pnpm -v'
      node: 
        cwd: ''
        command: 'node -v'
    test:
      npm:
        cwd: 'public/npm-install-test'
        command: 'npm install'
      cnpm:
        cwd: 'public/npm-install-test'
        command: 'cnpm install'
      yarn:
        cwd: 'public/npm-install-test'
        command: yarn install
      pnpm:
        cwd: 'public/npm-install-test'
        command: pnpm install
      ni:
        cwd: 'public/npm-install-test'
        command: ni install
    web-install:
      npm:
        cwd: 'web'
        command: 'npm install'
      cnpm:
        cwd: 'web'
        command: 'cnpm install'
      yarn:
        cwd: 'web'
        command: 'yarn install'
      pnpm:
        cwd: 'web'
        command: 'pnpm install'
      ni:
        cwd: 'web'
        command: 'ni install'
    nuxt-install:
      npm:
        cwd: 'web-nuxt'
        command: 'npm install'
      cnpm:
        cwd: 'web-nuxt'
        command: 'cnpm install'
      yarn:
        cwd: 'web-nuxt'
        command: 'yarn install'
      pnpm:
        cwd: 'web-nuxt'
        command: 'pnpm install'
      ni:
        cwd: 'web-nuxt'
        command: 'ni install'
    web-build:
      npm:
        cwd: 'web'
        command: 'npm run build'
      cnpm:
        cwd: 'web'
        command: 'cnpm run build'
      yarn:
        cwd: 'web'
        command: 'yarn run build'
      pnpm:
        cwd: 'web'
        command: 'pnpm run build'
      ni:
        cwd: 'web'
        command: 'nr build'
    set-registry:
      npm: 
        cwd: ''
        command: 'npm config set registry https://registry.npmjs.org/ && npm config get registry'
      taobao: 
        cwd: ''
        command: 'npm config set registry https://registry.npm.taobao.org/ && npm config get registry'
      rednpm:
        cwd: ''
        command: 'npm config set registry http://registry.mirror.cqupt.edu.cn/ && npm config get registry'
    ping:
      baidu: 
        cwd: ''
        command: 'ping baidu.com'
      localhost: 
        cwd: ''
        command: 'ping 127.0.0.1 -n 6'




