// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

// AdminClosure 管理员层级闭包表
type AdminClosure struct {
	AncestorID   int32 `gorm:"column:ancestor_id;type:int(11) unsigned;not null;primaryKey;comment:祖先ID;index:idx_ancestor_depth,priority:1;index:idx_descendant_ancestor,priority:2" json:"ancestor_id"` // 祖先ID
	DescendantID int32 `gorm:"column:descendant_id;type:int(11) unsigned;not null;primaryKey;comment:后代ID;index:idx_descendant_ancestor,priority:1" json:"descendant_id"`                                 // 后代ID
	Depth        int32 `gorm:"column:depth;type:int(11) unsigned;not null;comment:深度;index:idx_ancestor_depth,priority:2" json:"depth"`                                                                   // 深度
}
