// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-build-admin/app/admin/handler"
	"go-build-admin/app/admin/model"
	handler2 "go-build-admin/app/api/handler"
	"go-build-admin/app/cmd"
	handler3 "go-build-admin/app/cmd/handler"
	model2 "go-build-admin/app/common/model"
	"go-build-admin/app/common/model/country"
	"go-build-admin/app/cron"
	"go-build-admin/app/middleware"
	"go-build-admin/app/pkg/captcha"
	"go-build-admin/app/pkg/clickcaptcha"
	"go-build-admin/app/pkg/data_scope"
	"go-build-admin/app/pkg/terminal"
	"go-build-admin/app/pkg/token"
	"go-build-admin/conf"
	"go-build-admin/router"
	"go-build-admin/service/db"
	"go-build-admin/service/rds"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	gormDB := db.NewDB(configuration, zapLogger)
	client := rds.NewRedis(configuration, zapLogger)
	tokenHelper := token.NewTokenHelper(configuration, zapLogger, gormDB, client)
	authModel := model.NewAuthModel(gormDB, tokenHelper, configuration)
	login := middleware.NewLogin(configuration, tokenHelper, authModel)
	closureEnforcer := data_scope.NewClosureEnforcer(configuration)
	security := middleware.NewSecurity(configuration, zapLogger, gormDB, closureEnforcer)
	modelAuthModel := model2.NewAuthModel(gormDB, tokenHelper, configuration)
	userLogin := middleware.NewUserLogin(configuration, tokenHelper, modelAuthModel)
	adminLogModel := model.NewAdminLogModel(gormDB, configuration)
	record := middleware.NewRecord(configuration, adminLogModel)
	configModel := model.NewConfigModel(gormDB, configuration)
	service := country.NewService(gormDB, configuration)
	clickCaptcha := clickcaptcha.NewClickCaptcha(configuration, gormDB)
	indexHandler := handler.NewIndexHandler(configuration, zapLogger, authModel, configModel, service, clickCaptcha)
	areaModel := model2.NewAreaModel(gormDB, configuration)
	tableModel := model.NewTableModel(configuration, gormDB)
	aliossStorage := model2.NewAliossStorage(gormDB, configuration)
	uploadHelper := model2.NewUploadHelper(gormDB, configuration, aliossStorage)
	terminalTerminal := terminal.NewTerminal(configuration, zapLogger, authModel)
	ajaxHandler := handler.NewAjaxHandler(zapLogger, areaModel, tableModel, uploadHelper, terminalTerminal, configuration)
	installHandler := handler2.NewInstallHandler(zapLogger, configuration, terminalTerminal)
	countryLanguageModel := model.NewCountryLanguageModel(gormDB, configuration, closureEnforcer)
	countryLanguageHandler := handler.NewCountryLanguageHandler(zapLogger, countryLanguageModel)
	countryLanguageRegistrar := handler.NewCountryLanguageRegistrar(countryLanguageHandler)
	countryCurrencyModel := model.NewCountryCurrencyModel(gormDB, configuration, closureEnforcer)
	countryCurrencyHandler := handler.NewCountryCurrencyHandler(zapLogger, countryCurrencyModel)
	countryCurrencyRegistrar := handler.NewCountryCurrencyRegistrar(countryCurrencyHandler)
	countryLanguageContentModel := model.NewCountryLanguageContentModel(gormDB, configuration, closureEnforcer)
	countryLanguageContentHandler := handler.NewCountryLanguageContentHandler(zapLogger, countryLanguageContentModel)
	countryLanguageContentRegistrar := handler.NewCountryLanguageContentRegistrar(countryLanguageContentHandler)
	crudLogModel := model.NewCrudLogModel(gormDB, configuration, closureEnforcer)
	crudLogHandler := handler.NewCrudLogHandler(zapLogger, crudLogModel, authModel)
	crudLogRegistrar := handler.NewCrudLogRegistrar(crudLogHandler)
	moduleHandler := handler.NewModuleHandler(zapLogger)
	moduleRegistrar := handler.NewModuleRegistrar(moduleHandler)
	testBuildModel := model.NewTestBuildModel(gormDB, configuration)
	testBuildHandler := handler.NewTestBuildHandler(zapLogger, testBuildModel)
	testBuildRegistrar := handler.NewTestBuildRegistrar(testBuildHandler)
	adminGroupModel := model.NewAdminGroupModel(gormDB, configuration)
	adminRuleModel := model.NewAdminRuleModel(gormDB, configuration)
	adminGroupHandler := handler.NewAdminGroupHandler(zapLogger, adminGroupModel, adminRuleModel, authModel)
	adminGroupRegistrar := handler.NewAdminGroupRegistrar(adminGroupHandler)
	adminRuleHandler := handler.NewAdminRuleHandler(zapLogger, adminRuleModel, authModel)
	adminRuleRegistrar := handler.NewAdminRuleRegistrar(adminRuleHandler)
	userGroupModel := model.NewUserGroupModel(gormDB, configuration)
	userGroupHandler := handler.NewUserGroupHandler(zapLogger, userGroupModel, adminRuleModel, authModel)
	userGroupRegistrar := handler.NewUserGroupRegistrar(userGroupHandler)
	userRuleModel := model.NewUserRuleModel(gormDB, configuration)
	userRuleHandler := handler.NewUserRuleHandler(zapLogger, userRuleModel, authModel)
	userRuleRegistrar := handler.NewUserRuleRegistrar(userRuleHandler)
	configHandler := handler.NewConfigHandler(zapLogger, configuration, configModel)
	configRegistrar := handler.NewConfigRegistrar(configHandler)
	attachmentModel := model2.NewAttachmentModel(gormDB, configuration, closureEnforcer)
	attachmentHandler := handler.NewAttachmentHandler(zapLogger, attachmentModel)
	attachmentRegistrar := handler.NewAttachmentRegistrar(attachmentHandler)
	adminModel := model.NewAdminModel(gormDB, configuration)
	adminHandler := handler.NewAdminHandler(zapLogger, adminModel, authModel)
	adminRegistrar := handler.NewAdminRegistrar(adminHandler)
	userModel := model.NewUserModel(gormDB, configuration, closureEnforcer)
	userHandler := handler.NewUserHandler(zapLogger, userModel)
	userRegistrar := handler.NewUserRegistrar(userHandler)
	dataRecycleModel := model.NewDataRecycleModel(gormDB, configuration, closureEnforcer)
	dataRecycleHandler := handler.NewDataRecycleHandler(zapLogger, configuration, dataRecycleModel, tableModel)
	dataRecycleRegistrar := handler.NewDataRecycleRegistrar(dataRecycleHandler)
	dataRecycleLogModel := model.NewDataRecycleLogModel(gormDB, configuration, closureEnforcer)
	dataRecycleLogHandler := handler.NewDataRecycleLogHandler(zapLogger, configuration, dataRecycleLogModel)
	dataRecycleLogRegistrar := handler.NewDataRecycleLogRegistrar(dataRecycleLogHandler)
	sensitiveDataModel := model.NewSensitiveDataModel(gormDB, configuration, closureEnforcer)
	sensitiveDataHandler := handler.NewSensitiveDataHandler(zapLogger, configuration, sensitiveDataModel, tableModel)
	sensitiveDataRegistrar := handler.NewSensitiveDataRegistrar(sensitiveDataHandler)
	sensitiveDataLogModel := model.NewSensitiveDataLogModel(gormDB, configuration, closureEnforcer)
	sensitiveDataLogHandler := handler.NewSensitiveDataLogHandler(zapLogger, configuration, sensitiveDataLogModel)
	sensitiveDataLogRegistrar := handler.NewSensitiveDataLogRegistrar(sensitiveDataLogHandler)
	adminInfoHandler := handler.NewAdminInfoHandler(zapLogger, adminModel, authModel)
	adminInfoRegistrar := handler.NewAdminInfoRegistrar(adminInfoHandler)
	adminLogHandler := handler.NewAdminLogHandler(zapLogger, adminLogModel)
	adminLogRegistrar := handler.NewAdminLogRegistrar(adminLogHandler)
	crudHandler := handler.NewCrudHandler(zapLogger, tableModel, crudLogModel, adminRuleModel, configuration)
	crudRegistrar := handler.NewCrudRegistrar(crudHandler)
	dashboardHandler := handler.NewDashboardHandler(zapLogger, adminRuleModel)
	dashboardRegistrar := handler.NewDashboardRegistrar(dashboardHandler)
	userMoneyLogModel := model.NewUserMoneyLogModel(gormDB, configuration, closureEnforcer)
	userMoneyLogHandler := handler.NewUserMoneyLogHandler(zapLogger, userMoneyLogModel)
	userScoreLogModel := model.NewUserScoreLogModel(gormDB, configuration, closureEnforcer)
	userScoreLogHandler := handler.NewUserScoreLogHandler(zapLogger, userScoreLogModel)
	userLogRegistrar := handler.NewUserLogRegistrar(userHandler, userMoneyLogHandler, userScoreLogHandler)
	modelUserModel := model2.NewUserModel(gormDB, configuration)
	modelUserScoreLogModel := model2.NewUserScoreLogModel(gormDB)
	modelUserMoneyLogModel := model2.NewUserMoneyLogModel(gormDB)
	captchaCaptcha := captcha.NewCaptcha(gormDB)
	accountHandler := handler2.NewAccountHandler(zapLogger, modelAuthModel, modelUserModel, modelUserScoreLogModel, modelUserMoneyLogModel, captchaCaptcha)
	accountRegistrar := handler2.NewAccountRegistrar(accountHandler)
	handlerAjaxHandler := handler2.NewAjaxHandler(zapLogger, areaModel, uploadHelper)
	ajaxRegistrar := handler2.NewAjaxRegistrar(handlerAjaxHandler)
	commonHandler := handler2.NewCommonHandler(zapLogger, clickCaptcha, captchaCaptcha, tokenHelper, configuration)
	commonRegistrar := handler2.NewCommonRegistrar(commonHandler)
	emsHandler := handler2.NewEmsHandler(zapLogger, configModel, captchaCaptcha, clickCaptcha, modelUserModel, modelAuthModel)
	emsRegistrar := handler2.NewEmsRegistrar(emsHandler)
	handlerIndexHandler := handler2.NewIndexHandler(zapLogger, modelAuthModel, configuration, configModel, service)
	indexRegistrar := handler2.NewIndexRegistrar(handlerIndexHandler)
	handlerUserHandler := handler2.NewUserHandler(zapLogger, configuration, modelAuthModel, clickCaptcha, captchaCaptcha)
	handlerUserRegistrar := handler2.NewUserRegistrar(handlerUserHandler)
	demoHandler := handler2.NewDemoHandler(zapLogger)
	demoRegistrar := handler2.NewDemoRegistrar(demoHandler)
	v := router.ProvideRegistrars(countryLanguageRegistrar, countryCurrencyRegistrar, countryLanguageContentRegistrar, crudLogRegistrar, moduleRegistrar, testBuildRegistrar, adminGroupRegistrar, adminRuleRegistrar, userGroupRegistrar, userRuleRegistrar, configRegistrar, attachmentRegistrar, adminRegistrar, userRegistrar, dataRecycleRegistrar, dataRecycleLogRegistrar, sensitiveDataRegistrar, sensitiveDataLogRegistrar, adminInfoRegistrar, adminLogRegistrar, crudRegistrar, dashboardRegistrar, userLogRegistrar, accountRegistrar, ajaxRegistrar, commonRegistrar, emsRegistrar, indexRegistrar, handlerUserRegistrar, demoRegistrar)
	engine := router.InitRouter(lumberjackLogger, login, security, userLogin, record, indexHandler, ajaxHandler, installHandler, v)
	server := newHttpServer(configuration, engine)
	exampleJob := cron.NewExampleJob(zapLogger)
	cronCron := cron.NewCron(gormDB, zapLogger, exampleJob)
	app := newApp(configuration, zapLogger, server, cronCron)
	return app, func() {
	}, nil
}

// wireCommand init application.
func wireCommand(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*cmd.Command, func(), error) {
	exampleHandler := handler3.NewExampleHandler(zapLogger)
	migrateHandler := handler3.NewMigrateHandler(zapLogger, configuration)
	crudHandler := handler3.NewCrudHandler(zapLogger, configuration)
	command := cmd.NewCommand(exampleHandler, migrateHandler, crudHandler)
	return command, func() {
	}, nil
}
