// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-build-admin/app/admin/handler"
	"go-build-admin/app/admin/model"
	handler2 "go-build-admin/app/api/handler"
	"go-build-admin/app/cron"
	"go-build-admin/app/middleware"
	"go-build-admin/app/pkg/clickcaptcha"
	"go-build-admin/app/pkg/token"
	"go-build-admin/conf"
	"go-build-admin/router"
	"go-build-admin/service/db"
	"go-build-admin/service/rds"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	gormDB := db.NewDB(configuration, zapLogger)
	client := rds.NewRedis(configuration, zapLogger)
	tokenHelper := token.NewTokenHelper(configuration, zapLogger, gormDB, client)
	authModel := model.NewAuthModel(gormDB, tokenHelper, configuration)
	login := middleware.NewLogin(configuration, tokenHelper, authModel)
	dataLimit := middleware.NewDataLimit(configuration, authModel)
	adminLogModel := model.NewAdminLogModel(gormDB)
	record := middleware.NewRecord(configuration, adminLogModel)
	adminModel := model.NewAdminModel(gormDB)
	adminHandler := handler.NewAdminHandler(zapLogger, adminModel, authModel)
	adminGroupModel := model.NewAdminGroupModel(gormDB)
	adminRuleModel := model.NewAdminRuleModel(gormDB)
	adminGroupHandler := handler.NewAdminGroupHandler(zapLogger, adminGroupModel, adminRuleModel, authModel)
	adminLogHandler := handler.NewAdminLogHandler(zapLogger, adminLogModel)
	testBuildModel := model.NewTestBuildModel(gormDB)
	testBuildHandler := handler.NewTestBuildHandler(zapLogger, testBuildModel)
	configModel := model.NewConfigModel(gormDB)
	clickCaptcha := clickcaptcha.NewCaptcha(configuration, gormDB)
	indexHandler := handler.NewIndexHandler(configuration, zapLogger, authModel, configModel, clickCaptcha)
	dashboardHandler := handler.NewDashboardHandler(zapLogger, adminRuleModel)
	accountHandler := handler2.NewAccountHandler(zapLogger)
	ajaxHandler := handler2.NewAjaxHandler(zapLogger)
	commonHandler := handler2.NewCommonHandler(zapLogger, clickCaptcha)
	emsHandler := handler2.NewEmsHandler(zapLogger)
	handlerIndexHandler := handler2.NewIndexHandler(zapLogger)
	installHandler := handler2.NewInstallHandler(zapLogger)
	userHandler := handler2.NewUserHandler(zapLogger)
	engine := router.InitRouter(lumberjackLogger, login, dataLimit, record, adminHandler, adminGroupHandler, adminLogHandler, testBuildHandler, indexHandler, dashboardHandler, accountHandler, ajaxHandler, commonHandler, emsHandler, handlerIndexHandler, installHandler, userHandler)
	server := newHttpServer(configuration, engine)
	exampleJob := cron.NewExampleJob(zapLogger)
	cronCron := cron.NewCron(gormDB, zapLogger, exampleJob)
	app := newApp(configuration, zapLogger, server, cronCron)
	return app, func() {
	}, nil
}
