// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-build-admin/app/admin/handler"
	auth2 "go-build-admin/app/admin/handler/auth"
	country3 "go-build-admin/app/admin/handler/country"
	crud2 "go-build-admin/app/admin/handler/crud"
	routine2 "go-build-admin/app/admin/handler/routine"
	security2 "go-build-admin/app/admin/handler/security"
	user2 "go-build-admin/app/admin/handler/user"
	model2 "go-build-admin/app/admin/model"
	"go-build-admin/app/admin/model/auth"
	country2 "go-build-admin/app/admin/model/country"
	"go-build-admin/app/admin/model/crud"
	"go-build-admin/app/admin/model/routine"
	"go-build-admin/app/admin/model/security"
	"go-build-admin/app/admin/model/user"
	handler2 "go-build-admin/app/api/handler"
	user3 "go-build-admin/app/api/model/user"
	"go-build-admin/app/cmd"
	handler3 "go-build-admin/app/cmd/handler"
	"go-build-admin/app/common/member"
	"go-build-admin/app/common/model"
	"go-build-admin/app/common/model/country"
	"go-build-admin/app/cron"
	"go-build-admin/app/middleware"
	"go-build-admin/app/pkg/captcha"
	"go-build-admin/app/pkg/clickcaptcha"
	"go-build-admin/app/pkg/data_scope"
	"go-build-admin/app/pkg/terminal"
	"go-build-admin/app/pkg/token"
	"go-build-admin/conf"
	"go-build-admin/router"
	"go-build-admin/service/db"
	"go-build-admin/service/rds"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	gormDB := db.NewDB(configuration, zapLogger)
	client := rds.NewRedis(configuration, zapLogger)
	tokenHelper := token.NewTokenHelper(configuration, zapLogger, gormDB, client)
	authModel := auth.NewAuthModel(gormDB, tokenHelper, configuration)
	authorization := middleware.NewAuthorization(authModel, zapLogger)
	login := middleware.NewLogin(configuration, tokenHelper, authModel)
	closureEnforcer := data_scope.NewClosureEnforcer(configuration)
	middlewareSecurity := middleware.NewSecurity(configuration, zapLogger, gormDB, closureEnforcer)
	service := member.NewService(gormDB, tokenHelper, configuration)
	userLogin := middleware.NewUserLogin(configuration, tokenHelper, service)
	adminLogModel := auth.NewAdminLogModel(gormDB, configuration)
	record := middleware.NewRecord(configuration, adminLogModel)
	configModel := routine.NewConfigModel(gormDB, configuration)
	countryService := country.NewService(gormDB, configuration)
	clickCaptcha := clickcaptcha.NewClickCaptcha(configuration, gormDB)
	indexHandler := handler.NewIndexHandler(configuration, zapLogger, authModel, configModel, countryService, clickCaptcha)
	areaModel := model.NewAreaModel(gormDB, configuration)
	tableModel := model2.NewTableModel(configuration, gormDB)
	aliossStorage := model.NewAliossStorage(gormDB, configuration)
	uploadHelper := model.NewUploadHelper(gormDB, configuration, aliossStorage)
	terminalTerminal := terminal.NewTerminal(configuration, zapLogger, authModel)
	ajaxHandler := handler.NewAjaxHandler(zapLogger, areaModel, tableModel, uploadHelper, terminalTerminal, configuration)
	installHandler := handler2.NewInstallHandler(zapLogger, configuration, terminalTerminal)
	logModel := crud.NewLogModel(gormDB, configuration, closureEnforcer)
	logHandler := crud2.NewLogHandler(zapLogger, logModel, authModel)
	logRegistrar := crud2.NewLogRegistrar(logHandler)
	moduleHandler := handler.NewModuleHandler(zapLogger)
	moduleRegistrar := handler.NewModuleRegistrar(moduleHandler)
	testBuildModel := model2.NewTestBuildModel(gormDB, configuration)
	testBuildHandler := handler.NewTestBuildHandler(zapLogger, testBuildModel)
	testBuildRegistrar := handler.NewTestBuildRegistrar(testBuildHandler)
	adminGroupModel := auth.NewAdminGroupModel(gormDB, configuration)
	adminRuleModel := auth.NewAdminRuleModel(gormDB, configuration)
	adminGroupHandler := auth2.NewAdminGroupHandler(zapLogger, adminGroupModel, adminRuleModel, authModel)
	adminGroupRegistrar := auth2.NewAdminGroupRegistrar(adminGroupHandler)
	adminRuleHandler := auth2.NewAdminRuleHandler(zapLogger, adminRuleModel, authModel)
	adminRuleRegistrar := auth2.NewAdminRuleRegistrar(adminRuleHandler)
	groupModel := user.NewGroupModel(gormDB, configuration)
	memberPermissionInvalidator := user2.NewMemberPermissionInvalidator(service)
	groupHandler := user2.NewGroupHandlerWithAuth(zapLogger, groupModel, adminRuleModel, authModel, memberPermissionInvalidator)
	groupRegistrar := user2.NewGroupRegistrar(groupHandler)
	ruleModel := user.NewRuleModel(gormDB, configuration)
	ruleHandler := user2.NewRuleHandlerWithAuth(zapLogger, ruleModel, authModel, memberPermissionInvalidator)
	ruleRegistrar := user2.NewRuleRegistrar(ruleHandler)
	configHandler := routine2.NewConfigHandler(zapLogger, configuration, configModel)
	configRegistrar := routine2.NewConfigRegistrar(configHandler)
	attachmentModel := model.NewAttachmentModel(gormDB, configuration, closureEnforcer)
	attachmentHandler := routine2.NewAttachmentHandler(zapLogger, attachmentModel)
	attachmentRegistrar := routine2.NewAttachmentRegistrar(attachmentHandler)
	adminModel := auth.NewAdminModel(gormDB, configuration)
	adminHandler := auth2.NewAdminHandler(zapLogger, adminModel, authModel)
	adminRegistrar := auth2.NewAdminRegistrar(adminHandler)
	userModel := user.NewUserModel(gormDB, configuration, closureEnforcer)
	userHandler := user2.NewUserHandlerWithAuth(zapLogger, userModel, memberPermissionInvalidator)
	userRegistrar := user2.NewUserRegistrar(userHandler)
	dataRecycleModel := security.NewDataRecycleModel(gormDB, configuration, closureEnforcer)
	dataRecycleHandler := security2.NewDataRecycleHandler(zapLogger, configuration, dataRecycleModel, tableModel)
	dataRecycleRegistrar := security2.NewDataRecycleRegistrar(dataRecycleHandler)
	dataRecycleLogModel := security.NewDataRecycleLogModel(gormDB, configuration, closureEnforcer)
	dataRecycleLogHandler := security2.NewDataRecycleLogHandler(zapLogger, configuration, dataRecycleLogModel)
	dataRecycleLogRegistrar := security2.NewDataRecycleLogRegistrar(dataRecycleLogHandler)
	sensitiveDataModel := security.NewSensitiveDataModel(gormDB, configuration, closureEnforcer)
	sensitiveDataHandler := security2.NewSensitiveDataHandler(zapLogger, configuration, sensitiveDataModel, tableModel)
	sensitiveDataRegistrar := security2.NewSensitiveDataRegistrar(sensitiveDataHandler)
	sensitiveDataLogModel := security.NewSensitiveDataLogModel(gormDB, configuration, closureEnforcer)
	sensitiveDataLogHandler := security2.NewSensitiveDataLogHandler(zapLogger, configuration, sensitiveDataLogModel)
	sensitiveDataLogRegistrar := security2.NewSensitiveDataLogRegistrar(sensitiveDataLogHandler)
	adminInfoHandler := routine2.NewAdminInfoHandler(zapLogger, adminModel, authModel)
	adminInfoRegistrar := routine2.NewAdminInfoRegistrar(adminInfoHandler)
	adminLogHandler := auth2.NewAdminLogHandler(zapLogger, adminLogModel)
	adminLogRegistrar := auth2.NewAdminLogRegistrar(adminLogHandler)
	crudHandler := crud2.NewCrudHandler(zapLogger, tableModel, logModel, adminRuleModel, configuration)
	crudRegistrar := crud2.NewCrudRegistrar(crudHandler)
	dashboardHandler := handler.NewDashboardHandler(zapLogger, adminRuleModel)
	dashboardRegistrar := handler.NewDashboardRegistrar(dashboardHandler)
	moneyLogModel := user.NewMoneyLogModel(gormDB, configuration, closureEnforcer)
	moneyLogHandler := user2.NewMoneyLogHandler(zapLogger, moneyLogModel)
	scoreLogModel := user.NewScoreLogModel(gormDB, configuration, closureEnforcer)
	scoreLogHandler := user2.NewScoreLogHandler(zapLogger, scoreLogModel)
	userLogRegistrar := user2.NewUserLogRegistrar(userHandler, moneyLogHandler, scoreLogHandler)
	userUserModel := user3.NewUserModel(gormDB, configuration)
	userScoreLogModel := user3.NewUserScoreLogModel(gormDB)
	userMoneyLogModel := user3.NewUserMoneyLogModel(gormDB)
	captchaCaptcha := captcha.NewCaptcha(gormDB)
	accountHandler := handler2.NewAccountHandler(zapLogger, service, userUserModel, userScoreLogModel, userMoneyLogModel, captchaCaptcha)
	accountRegistrar := handler2.NewAccountRegistrar(accountHandler)
	handlerAjaxHandler := handler2.NewAjaxHandler(zapLogger, areaModel, uploadHelper)
	ajaxRegistrar := handler2.NewAjaxRegistrar(handlerAjaxHandler)
	commonHandler := handler2.NewCommonHandler(zapLogger, clickCaptcha, captchaCaptcha, tokenHelper, configuration)
	commonRegistrar := handler2.NewCommonRegistrar(commonHandler)
	emsHandler := handler2.NewEmsHandler(zapLogger, configModel, captchaCaptcha, clickCaptcha, userUserModel, service)
	emsRegistrar := handler2.NewEmsRegistrar(emsHandler)
	handlerIndexHandler := handler2.NewIndexHandler(zapLogger, service, configuration, configModel, countryService)
	indexRegistrar := handler2.NewIndexRegistrar(handlerIndexHandler)
	handlerUserHandler := handler2.NewUserHandler(zapLogger, configuration, service, clickCaptcha, captchaCaptcha)
	handlerUserRegistrar := handler2.NewUserRegistrar(handlerUserHandler)
	demoHandler := handler2.NewDemoHandler(zapLogger)
	demoRegistrar := handler2.NewDemoRegistrar(demoHandler)
	currencyModel := country2.NewCurrencyModel(gormDB, configuration, closureEnforcer)
	currencyHandler := country3.NewCurrencyHandler(zapLogger, currencyModel)
	currencyRegistrar := country3.NewCurrencyRegistrar(currencyHandler)
	languageModel := country2.NewLanguageModel(gormDB, configuration, closureEnforcer)
	languageHandler := country3.NewLanguageHandler(zapLogger, languageModel)
	languageRegistrar := country3.NewLanguageRegistrar(languageHandler)
	languageContentModel := country2.NewLanguageContentModel(gormDB, configuration, closureEnforcer)
	languageContentHandler := country3.NewLanguageContentHandler(zapLogger, languageContentModel)
	languageContentRegistrar := country3.NewLanguageContentRegistrar(languageContentHandler)
	v := router.ProvideRegistrars(logRegistrar, moduleRegistrar, testBuildRegistrar, adminGroupRegistrar, adminRuleRegistrar, groupRegistrar, ruleRegistrar, configRegistrar, attachmentRegistrar, adminRegistrar, userRegistrar, dataRecycleRegistrar, dataRecycleLogRegistrar, sensitiveDataRegistrar, sensitiveDataLogRegistrar, adminInfoRegistrar, adminLogRegistrar, crudRegistrar, dashboardRegistrar, userLogRegistrar, accountRegistrar, ajaxRegistrar, commonRegistrar, emsRegistrar, indexRegistrar, handlerUserRegistrar, demoRegistrar, currencyRegistrar, languageRegistrar, languageContentRegistrar)
	engine := router.InitRouter(lumberjackLogger, login, authorization, middlewareSecurity, userLogin, record, indexHandler, ajaxHandler, installHandler, v)
	server := newHttpServer(configuration, engine)
	exampleJob := cron.NewExampleJob(zapLogger)
	cronCron := cron.NewCron(gormDB, zapLogger, exampleJob)
	app := newApp(configuration, zapLogger, authorization, server, cronCron)
	return app, func() {
	}, nil
}

// wireCommand init application.
func wireCommand(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*cmd.Command, func(), error) {
	exampleHandler := handler3.NewExampleHandler(zapLogger)
	migrateHandler := handler3.NewMigrateHandler(zapLogger, configuration)
	crudHandler := handler3.NewCrudHandler(zapLogger, configuration)
	command := cmd.NewCommand(exampleHandler, migrateHandler, crudHandler)
	return command, func() {
	}, nil
}
