package crud_helper

import (
	"go-build-admin/app/admin/model"
)

func getTestTableData() model.Table {
	table := model.Table{
		Name:             "test1",
		Comment:          "测试表",
		QuickSearchField: []string{"id"},
		DefaultSortField: "weigh",
		FormFields: []string{
			"weigh",
			"status",
			"remark11",
			"banner_id",
			"string",
			"image",
			"file",
			"radio",
			"checkbox",
			"select",
			"switch",
			"editor",
			"textarea",
			"number",
			"float",
			"password",
			"date",
			"time",
			"datetime",
			"year",
			"timestamp",
			"array",
			"city",
			"icon",
			"color",
			"images",
			"files",
			"selects",
			"team_ids"},
		ColumnFields: []string{
			"id",
			"weigh",
			"status",
			"update_time",
			"create_time",
			"string",
			"image",
			"radio",
			"checkbox",
			"select",
			"switch",
			"number",
			"float",
			"date",
			"time",
			"datetime",
			"year",
			"timestamp",
			"city",
			"icon",
			"color",
			"images",
			"selects"},
		DefaultSortType:      "desc",
		GenerateRelativePath: "test1",
		IsCommonModel:        0,
		ModelFile:            "app\\admin\\model\\Test1.go",
		ControllerFile:       "app\\admin\\handler\\Test1.go",
		ValidateFile:         "app\\admin\\validate\\Test1.go",
		WebViewsDir:          "web\\src\\views\\backend\\test1",
		DesignChange: []model.ChangeField{
			{
				Type:    "change-field-name",
				Index:   3,
				OldName: "remark",
				NewName: "remark11",
				Sync:    true,
			},
		},
		Rebuild: "No",
		Empty:   true,
	}
	return table
}

func getTestFieldData() []model.Field {
	fields := []model.Field{}
	fields = append(fields, model.Field{
		Title:             "主键",
		Name:              "id",
		DataType:          "",
		Comment:           "ID",
		DesignType:        "pk",
		TableBuildExclude: "",
		FormBuildExclude:  "1",
		Table: model.TableAttr{
			Width:    "70",
			Operator: "eq",
			Sortable: "custom",
		},
		Form:               model.FormAttr{},
		Type:               "int",
		Length:             "10",
		Precision:          "0",
		Default:            "none",
		Null:               "",
		PrimaryKey:         "1",
		Unsigned:           "1",
		AutoIncrement:      "1",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "权重（拖拽排序）",
		Name:              "weigh",
		DataType:          "",
		Comment:           "权重",
		DesignType:        "weigh",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
			Sortable: "custom",
		},
		Form: model.FormAttr{
			Validator: []string{
				"number",
				"required",
			},
			ValidatorMsg: "请输入数字",
		},
		Type:       "int",
		Length:     "8",
		Precision:  "0",
		Default:    "0",
		Null:       "1",
		PrimaryKey: "",
		Unsigned:   "1",
	})

	fields = append(fields, model.Field{
		Title:             "状态",
		Name:              "status",
		DataType:          "",
		Comment:           "状态:0=禁用,1=启用",
		DesignType:        "switch",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
			Sortable: "false",
			Render:   "switch",
		},
		Form:               model.FormAttr{},
		Type:               "tinyint",
		Length:             "1",
		Precision:          "0",
		Default:            "1",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "1",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "备注",
		Name:              "remark11",
		DataType:          "",
		Comment:           "备注",
		DesignType:        "textarea",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
		},
		Form: model.FormAttr{
			Validator:    []string{"required"},
			ValidatorMsg: "",
			Rows:         "3",
		},
		Type:               "varchar",
		Length:             "255",
		Precision:          "0",
		Default:            "empty string",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "修改时间",
		Name:              "update_time",
		DataType:          "",
		Comment:           "修改时间",
		DesignType:        "timestamp",
		TableBuildExclude: "",
		FormBuildExclude:  "1",
		Table: model.TableAttr{
			Width:      "160",
			Operator:   "RANGE",
			Sortable:   "custom",
			Render:     "datetime",
			TimeFormat: "yyyy-mm-dd hh:MM:ss",
		},
		Form: model.FormAttr{
			Validator:    []string{"date"},
			ValidatorMsg: "",
		},
		Type:               "bigint",
		Length:             "16",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "1",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "创建时间",
		Name:              "create_time",
		DataType:          "",
		Comment:           "创建时间",
		DesignType:        "timestamp",
		TableBuildExclude: "",
		FormBuildExclude:  "1",
		Table: model.TableAttr{
			Width:      "160",
			Operator:   "RANGE",
			Sortable:   "custom",
			Render:     "datetime",
			TimeFormat: "yyyy-mm-dd hh:MM:ss",
		},
		Form: model.FormAttr{
			Validator:    []string{"date"},
			ValidatorMsg: "",
		},
		Type:               "bigint",
		Length:             "16",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "1",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "远程下拉（关联表）",
		Name:              "banner_id",
		DataType:          "",
		Comment:           "远程下拉",
		DesignType:        "remoteSelect",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
		},
		Form: model.FormAttr{
			Validator:        []string{},
			ValidatorMsg:     "",
			Rows:             "",
			SelectMulti:      "",
			RemotePk:         "id",
			RemoteField:      "name",
			RemoteTable:      "banner",
			RemoteController: "app\\admin\\controller\\Banner.go",
			RemoteModel:      "app\\admin\\model\\Banner.go",
			RemoteUrl:        "",
			RelationFields:   "name",
		},
		Type:               "int",
		Length:             "10",
		Precision:          "0",
		Default:            "0",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "1",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "字符串",
		Name:              "string",
		DataType:          "",
		Comment:           "字符串",
		DesignType:        "string",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "LIKE",
			Sortable: "false",
			Render:   "none",
		},
		Form:               model.FormAttr{},
		Type:               "varchar",
		Length:             "200",
		Precision:          "0",
		Default:            "empty string",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "图片",
		Name:              "image",
		DataType:          "",
		Comment:           "图片",
		DesignType:        "image",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
			Render:   "image",
		},
		Form:               model.FormAttr{},
		Type:               "varchar",
		Length:             "200",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "文件",
		Name:              "file",
		DataType:          "",
		Comment:           "文件",
		DesignType:        "file",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
			Render:   "none",
		},
		Form:               model.FormAttr{},
		Type:               "varchar",
		Length:             "200",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "单选框",
		Name:              "radio",
		DataType:          "enum('opt0','opt1')",
		Comment:           "单选框:opt0=选项一,opt1=选项二",
		DesignType:        "radio",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
			Sortable: "false",
			Render:   "tag",
		},
		Form:               model.FormAttr{},
		Type:               "enum",
		Length:             "0",
		Precision:          "0",
		Default:            "opt0",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "数字",
		Name:              "number",
		DataType:          "",
		Comment:           "数字",
		DesignType:        "number",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Width:      "",
			Operator:   "RANGE",
			Sortable:   "false",
			Render:     "none",
			TimeFormat: "",
		},
		Form: model.FormAttr{
			Validator: []string{"number"},
			Step:      "1",
		},
		Type:               "int",
		Length:             "10",
		Precision:          "0",
		Default:            "0",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "日期",
		Name:              "date",
		DataType:          "",
		Comment:           "日期",
		DesignType:        "date",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Width:      "",
			Operator:   "eq",
			Sortable:   "custom",
			Render:     "",
			TimeFormat: "",
		},
		Form: model.FormAttr{
			Validator:    []string{"date"},
			ValidatorMsg: "",
		},
		Type:               "date",
		Length:             "0",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "时间日期（时间戳存储）",
		Name:              "timestamp",
		DataType:          "",
		Comment:           "时间日期",
		DesignType:        "timestamp",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Width:      "160",
			Operator:   "RANGE",
			Sortable:   "custom",
			Render:     "datetime",
			TimeFormat: "yyyy-mm-dd hh:MM:ss",
		},
		Form: model.FormAttr{
			Validator:    []string{"date"},
			ValidatorMsg: "",
		},
		Type:               "bigint",
		Length:             "16",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "1",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "年份",
		Name:              "year",
		DataType:          "",
		Comment:           "年份",
		DesignType:        "year",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "RANGE",
			Sortable: "custom",
		},
		Form: model.FormAttr{
			Validator:    []string{"date"},
			ValidatorMsg: "",
		},
		Type:               "year",
		Length:             "4",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "时间日期",
		Name:              "datetime",
		DataType:          "",
		Comment:           "时间日期",
		DesignType:        "datetime",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Width:    "160",
			Operator: "eq",
			Sortable: "custom",
		},
		Form: model.FormAttr{
			Validator:    []string{"date"},
			ValidatorMsg: "",
		},
		Type:               "datetime",
		Length:             "0",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "时间",
		Name:              "time",
		DataType:          "",
		Comment:           "时间",
		DesignType:        "time",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
			Sortable: "custom",
		},
		Form: model.FormAttr{
			Validator:    []string{},
			ValidatorMsg: "",
		},
		Type:               "time",
		Length:             "0",
		Precision:          "0",
		Default:            "null",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "密码",
		Name:              "password",
		DataType:          "",
		Comment:           "密码",
		DesignType:        "password",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
		},
		Form: model.FormAttr{
			Validator:    []string{"password"},
			ValidatorMsg: "",
		},
		Type:               "varchar",
		Length:             "32",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "浮点数",
		Name:              "float",
		DataType:          "",
		Comment:           "浮点数",
		DesignType:        "float",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "RANGE",
			Sortable: "false",
			Render:   "none",
		},
		Form: model.FormAttr{
			Validator: []string{"float"},
			Step:      "1",
		},
		Type:               "decimal",
		Length:             "6",
		Precision:          "2",
		Default:            "",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "复选框",
		Name:              "checkbox",
		DataType:          "set('opt0','opt1')",
		Comment:           "复选框:opt0=选项一,opt1=选项二",
		DesignType:        "checkbox",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "FIND_IN_SET",
			Sortable: "false",
			Render:   "tags",
		},
		Form:               model.FormAttr{},
		Type:               "set",
		Length:             "0",
		Precision:          "0",
		Default:            "opt0,opt1",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "多行文本框",
		Name:              "textarea",
		DataType:          "",
		Comment:           "多行文本框",
		DesignType:        "textarea",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
		},
		Form: model.FormAttr{
			Validator:    []string{},
			ValidatorMsg: "",
			Rows:         "3",
		},
		Type:               "varchar",
		Length:             "255",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "富文本",
		Name:              "editor",
		DataType:          "",
		Comment:           "富文本",
		DesignType:        "editor",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
		},
		Form: model.FormAttr{
			Validator:    []string{"editorRequired"},
			ValidatorMsg: "",
		},
		Type:               "text",
		Length:             "0",
		Precision:          "0",
		Default:            "empty string",
		Null:               "1",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "下拉框",
		Name:              "select",
		DataType:          "enum('opt0','opt1')",
		Comment:           "下拉框:opt0=选项一,opt1=选项二",
		DesignType:        "select",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
			Sortable: "false",
			Render:   "tag",
		},
		Form:               model.FormAttr{},
		Type:               "enum",
		Length:             "0",
		Precision:          "0",
		Default:            "opt0",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "城市选择",
		Name:              "city",
		DataType:          "",
		Comment:           "城市选择",
		DesignType:        "city",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
		},
		Form:               model.FormAttr{},
		Type:               "varchar",
		Length:             "100",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "数组",
		Name:              "array",
		DataType:          "",
		Comment:           "数组",
		DesignType:        "array",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
		},
		Form:               model.FormAttr{},
		Type:               "varchar",
		Length:             "255",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "下拉框（多选）",
		Name:              "selects",
		DataType:          "",
		Comment:           "下拉框:opt0=选项一,opt1=选项二",
		DesignType:        "selects",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "FIND_IN_SET",
			Sortable: "false",
			Render:   "tags",
		},
		Form: model.FormAttr{
			Validator:    []string{},
			ValidatorMsg: "",
			Rows:         "",
			SelectMulti:  "1",
		},
		Type:               "varchar",
		Length:             "100",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "远程下拉（关联多选）",
		Name:              "team_ids",
		DataType:          "",
		Comment:           "远程下拉",
		DesignType:        "remoteSelects",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "LIKE",
		},
		Form: model.FormAttr{
			Validator:        []string{},
			ValidatorMsg:     "",
			SelectMulti:      "1",
			RemotePk:         "id",
			RemoteField:      "name",
			RemoteTable:      "team",
			RemoteController: "app\\admin\\controller\\Team.go",
			RemoteModel:      "app\\admin\\model\\Team.go",
			RemoteUrl:        "",
			RelationFields:   "name",
		},
		Type:               "varchar",
		Length:             "100",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "文件（多选）",
		Name:              "files",
		DataType:          "",
		Comment:           "文件",
		DesignType:        "files",
		TableBuildExclude: "1",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
			Render:   "none",
		},
		Form: model.FormAttr{
			Validator:    []string{},
			ValidatorMsg: "",
			FileMulti:    "1",
		},
		Type:               "varchar",
		Length:             "255",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "图片（多选）",
		Name:              "images",
		DataType:          "",
		Comment:           "图片",
		DesignType:        "images",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
			Render:   "images",
		},
		Form: model.FormAttr{
			Validator:  []string{},
			ImageMulti: "1",
		},
		Type:               "varchar",
		Length:             "255",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "颜色选择器",
		Name:              "color",
		DataType:          "",
		Comment:           "颜色选择器",
		DesignType:        "color",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
			Render:   "color",
		},
		Form: model.FormAttr{
			Validator:    []string{},
			ValidatorMsg: "",
		},
		Type:               "varchar",
		Length:             "30",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})
	fields = append(fields, model.Field{
		Title:             "开关",
		Name:              "switch",
		DataType:          "",
		Comment:           "开关:0=关,1=开",
		DesignType:        "switch",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "eq",
			Sortable: "false",
			Render:   "switch",
		},
		Form:               model.FormAttr{},
		Type:               "tinyint",
		Length:             "1",
		Precision:          "0",
		Default:            "1",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "1",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})

	fields = append(fields, model.Field{
		Title:             "图标选择",
		Name:              "icon",
		DataType:          "",
		Comment:           "图标选择",
		DesignType:        "icon",
		TableBuildExclude: "",
		FormBuildExclude:  "",
		Table: model.TableAttr{
			Operator: "false",
			Render:   "icon",
		},
		Form:               model.FormAttr{},
		Type:               "varchar",
		Length:             "50",
		Precision:          "0",
		Default:            "empty string",
		Null:               "",
		PrimaryKey:         "",
		Unsigned:           "",
		AutoIncrement:      "",
		OriginalDesignType: "",
	})
	return fields
}
