// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaAnchorHot = "ba_anchor_hot"

// BaAnchorHot 主播热度
type BaAnchorHot struct {
	ID         int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AnchorID   int32 `gorm:"column:anchor_id;not null;comment:主播id" json:"anchor_id"`      // 主播id
	UserID     int32 `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`          // 用户id
	CreateTime int64 `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaAnchorHot's table name
func (*BaAnchorHot) TableName() string {
	return TableNameBaAnchorHot
}
