// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaAnchor = "ba_anchor"

// BaAnchor 主播表
type BaAnchor struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	Name       string    `gorm:"column:name;not null;comment:昵称" json:"name"`                         // 昵称
	Avatar     string    `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                     // 头像
	Birth      time.Time `gorm:"column:birth;comment:出生" json:"birth"`                                // 出生
	Sex        string    `gorm:"column:sex;not null;default:0;comment:性别:0=未知,1=男,2=女" json:"sex"`    // 性别:0=未知,1=男,2=女
	Images     string    `gorm:"column:images;not null;comment:图集" json:"images"`                     // 图集
	Hot        int32     `gorm:"column:hot;not null;comment:欢迎度" json:"hot"`                          // 欢迎度
	Signature  string    `gorm:"column:signature;not null;comment:签名" json:"signature"`               // 签名
	Weigh      int32     `gorm:"column:weigh;comment:权重" json:"weigh"`                                // 权重
	Status     bool      `gorm:"column:status;not null;default:1;comment:状态:0=禁用,1=启用" json:"status"` // 状态:0=禁用,1=启用
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`                  // 创建时间
	UpdateTime int64     `gorm:"column:update_time;comment:修改时间" json:"update_time"`                  // 修改时间
}

// TableName BaAnchor's table name
func (*BaAnchor) TableName() string {
	return TableNameBaAnchor
}
