// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaBanner = "ba_banner"

// BaBanner 轮播图
type BaBanner struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	Name       string `gorm:"column:name;not null;comment:名称" json:"name"`                         // 名称
	Image      string `gorm:"column:image;not null;comment:图片" json:"image"`                       // 图片
	Href       string `gorm:"column:href;not null;comment:跳转链接" json:"href"`                       // 跳转链接
	Weigh      int32  `gorm:"column:weigh;comment:权重" json:"weigh"`                                // 权重
	Status     bool   `gorm:"column:status;not null;default:1;comment:状态:0=禁用,1=启用" json:"status"` // 状态:0=禁用,1=启用
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                  // 创建时间
	UpdateTime int64  `gorm:"column:update_time;comment:修改时间" json:"update_time"`                  // 修改时间
}

// TableName BaBanner's table name
func (*BaBanner) TableName() string {
	return TableNameBaBanner
}
