// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaChatLog = "ba_chat_log"

// BaChatLog 聊天记录表
type BaChatLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`   // ID
	SendID     string    `gorm:"column:send_id;not null;default:0;comment:发送者id" json:"send_id"` // 发送者id
	SendName   string    `gorm:"column:send_name;not null;comment:发送者昵称" json:"send_name"`       // 发送者昵称
	ToID       string    `gorm:"column:to_id;not null;default:0;comment:接收者id" json:"to_id"`     // 接收者id
	ToName     string    `gorm:"column:to_name;not null;comment:接收者昵称" json:"to_name"`           // 接收者昵称
	Content    string    `gorm:"column:content;not null;comment:发送内容" json:"content"`            // 发送内容
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`             // 创建时间
}

// TableName BaChatLog's table name
func (*BaChatLog) TableName() string {
	return TableNameBaChatLog
}
