// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaCategory = "ba_category"

// BaCategory 无线级分类
type BaCategory struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;not null;comment:名称" json:"name"`                  // 名称
	Pid   int32  `gorm:"column:pid;not null;comment:上级" json:"pid"`                    // 上级
	Weigh int32  `gorm:"column:weigh;comment:权重" json:"weigh"`                         // 权重
}

// TableName BaCategory's table name
func (*BaCategory) TableName() string {
	return TableNameBaCategory
}
