// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaDataexport = "ba_dataexport"

// BaDataexport 导出任务表
type BaDataexport struct {
	ID                  int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                 // ID
	AdminID             int32  `gorm:"column:admin_id;not null;comment:导出人" json:"admin_id"`                                         // 导出人
	Name                string `gorm:"column:name;not null;comment:任务名称" json:"name"`                                                // 任务名称
	MainTable           string `gorm:"column:main_table;not null;comment:数据源表" json:"main_table"`                                    // 数据源表
	FieldConfig         string `gorm:"column:field_config;comment:字段配置" json:"field_config"`                                         // 字段配置
	JoinTable           string `gorm:"column:join_table;comment:关联表配置" json:"join_table"`                                            // 关联表配置
	WhereField          string `gorm:"column:where_field;comment:筛选规则" json:"where_field"`                                           // 筛选规则
	OrderField          string `gorm:"column:order_field;comment:排序规则" json:"order_field"`                                           // 排序规则
	XlsMaxNumber        int32  `gorm:"column:xls_max_number;not null;default:10000;comment:单个xls最大记录数" json:"xls_max_number"`        // 单个xls最大记录数
	ConcurrentCreateXls int32  `gorm:"column:concurrent_create_xls;not null;default:3;comment:并发创建xls" json:"concurrent_create_xls"` // 并发创建xls
	MemoryLimit         int32  `gorm:"column:memory_limit;not null;default:128;comment:脚本内存限制(MB)" json:"memory_limit"`              // 脚本内存限制(MB)
	ExportNumber        int32  `gorm:"column:export_number;comment:导出记录数" json:"export_number"`                                      // 导出记录数
	Subtask             string `gorm:"column:subtask;comment:子任务资料" json:"subtask"`                                                  // 子任务资料
	Lastprogress        int32  `gorm:"column:lastprogress;not null;comment:上次导出进度" json:"lastprogress"`                              // 上次导出进度
	Lastfile            string `gorm:"column:lastfile;not null;comment:上次导出文件" json:"lastfile"`                                      // 上次导出文件
	Lastexporttime      int32  `gorm:"column:lastexporttime;comment:上次导出时间" json:"lastexporttime"`                                   // 上次导出时间
	Createtime          int32  `gorm:"column:createtime;comment:创建时间" json:"createtime"`                                             // 创建时间
}

// TableName BaDataexport's table name
func (*BaDataexport) TableName() string {
	return TableNameBaDataexport
}
