// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaExamplesTableTree = "ba_examples_table_tree"

// BaExamplesTableTree 树形数据
type BaExamplesTableTree struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String     string    `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
	Date       time.Time `gorm:"column:date;comment:日期" json:"date"`                           // 日期
	Address    string    `gorm:"column:address;not null;comment:详细地址" json:"address"`          // 详细地址
	Code       string    `gorm:"column:code;not null;comment:邮编" json:"code"`                  // 邮编
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableTree's table name
func (*BaExamplesTableTree) TableName() string {
	return TableNameBaExamplesTableTree
}
