// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableFormSubmit = "ba_examples_table_form_submit"

// BaExamplesTableFormSubmit 表单提交前数据处理
type BaExamplesTableFormSubmit struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String string `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
}

// TableName BaExamplesTableFormSubmit's table name
func (*BaExamplesTableFormSubmit) TableName() string {
	return TableNameBaExamplesTableFormSubmit
}
