// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaExamplesTableFormOther = "ba_examples_table_form_other"

// BaExamplesTableFormOther 表单其他示例
type BaExamplesTableFormOther struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String     string    `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
	Number     int32     `gorm:"column:number;not null;comment:数字" json:"number"`              // 数字
	Datetime   time.Time `gorm:"column:datetime;comment:时间日期" json:"datetime"`                 // 时间日期
	Image      string    `gorm:"column:image;not null;comment:图片" json:"image"`                // 图片
	UserID     int32     `gorm:"column:user_id;not null;comment:会员ID" json:"user_id"`          // 会员ID
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableFormOther's table name
func (*BaExamplesTableFormOther) TableName() string {
	return TableNameBaExamplesTableFormOther
}
