// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaExamplesTableStatus = "ba_examples_table_status"

// BaExamplesTableStatus 带状态表格
type BaExamplesTableStatus struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String     string    `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
	Number     int32     `gorm:"column:number;not null;comment:数字" json:"number"`              // 数字
	Float      float64   `gorm:"column:float;not null;default:0.00;comment:浮点数" json:"float"`  // 浮点数
	Date       time.Time `gorm:"column:date;comment:日期" json:"date"`                           // 日期
	UpdateTime int64     `gorm:"column:update_time;comment:修改时间" json:"update_time"`           // 修改时间
	Datetime   time.Time `gorm:"column:datetime;comment:时间日期" json:"datetime"`                 // 时间日期
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableStatus's table name
func (*BaExamplesTableStatus) TableName() string {
	return TableNameBaExamplesTableStatus
}
