// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableRefresh = "ba_examples_table_refresh"

// BaExamplesTableRefresh 编程式刷新表格
type BaExamplesTableRefresh struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String string `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
}

// TableName BaExamplesTableRefresh's table name
func (*BaExamplesTableRefresh) TableName() string {
	return TableNameBaExamplesTableRefresh
}
