// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableSummary = "ba_examples_table_summary"

// BaExamplesTableSummary 表尾合计行
type BaExamplesTableSummary struct {
	ID         int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`   // ID
	Number1    int32   `gorm:"column:number1;not null;comment:数字1" json:"number1"`             // 数字1
	Number2    int32   `gorm:"column:number2;not null;comment:数字2" json:"number2"`             // 数字2
	Float1     float64 `gorm:"column:float1;not null;default:0.00;comment:浮点数1" json:"float1"` // 浮点数1
	Float2     float64 `gorm:"column:float2;not null;default:0.00;comment:浮点数2" json:"float2"` // 浮点数2
	CreateTime int64   `gorm:"column:create_time;comment:创建时间" json:"create_time"`             // 创建时间
}

// TableName BaExamplesTableSummary's table name
func (*BaExamplesTableSummary) TableName() string {
	return TableNameBaExamplesTableSummary
}
