// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaExamplesTableEvent2 = "ba_examples_table_event2"

// BaExamplesTableEvent2 表格事件监听2
type BaExamplesTableEvent2 struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`      // ID
	String     string    `gorm:"column:string;not null;comment:字符串" json:"string"`                  // 字符串
	Switch     int32     `gorm:"column:switch;not null;default:1;comment:开关:0=关,1=开" json:"switch"` // 开关:0=关,1=开
	Datetime   time.Time `gorm:"column:datetime;comment:时间日期" json:"datetime"`                      // 时间日期
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`                // 创建时间
}

// TableName BaExamplesTableEvent2's table name
func (*BaExamplesTableEvent2) TableName() string {
	return TableNameBaExamplesTableEvent2
}
