// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableFormEdit = "ba_examples_table_form_edit"

// BaExamplesTableFormEdit 数据编辑之前预处理
type BaExamplesTableFormEdit struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String string `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
}

// TableName BaExamplesTableFormEdit's table name
func (*BaExamplesTableFormEdit) TableName() string {
	return TableNameBaExamplesTableFormEdit
}
