// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaExamplesTableMheader = "ba_examples_table_mheader"

// BaExamplesTableMheader 多级表头示例
type BaExamplesTableMheader struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Date       time.Time `gorm:"column:date;comment:日期" json:"date"`                           // 日期
	UserID     int32     `gorm:"column:user_id;not null;comment:远程下拉" json:"user_id"`          // 远程下拉
	City       string    `gorm:"column:city;not null;comment:城市" json:"city"`                  // 城市
	Address    string    `gorm:"column:address;not null;comment:详细地址" json:"address"`          // 详细地址
	Code       string    `gorm:"column:code;not null;comment:邮编" json:"code"`                  // 邮编
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableMheader's table name
func (*BaExamplesTableMheader) TableName() string {
	return TableNameBaExamplesTableMheader
}
