// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableCellPre = "ba_examples_table_cell_pre"

// BaExamplesTableCellPre 预设渲染方案
type BaExamplesTableCellPre struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	String     string `gorm:"column:string;not null;comment:字符串" json:"string"`                    // 字符串
	URL        string `gorm:"column:url;not null;comment:链接" json:"url"`                           // 链接
	Image      string `gorm:"column:image;not null;comment:图片" json:"image"`                       // 图片
	Icon       string `gorm:"column:icon;not null;comment:图标选择" json:"icon"`                       // 图标选择
	Color      string `gorm:"column:color;not null;comment:颜色选择器" json:"color"`                    // 颜色选择器
	Status     int32  `gorm:"column:status;not null;default:1;comment:状态:0=禁用,1=启用" json:"status"` // 状态:0=禁用,1=启用
	Weigh      int32  `gorm:"column:weigh;comment:权重" json:"weigh"`                                // 权重
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                  // 创建时间
}

// TableName BaExamplesTableCellPre's table name
func (*BaExamplesTableCellPre) TableName() string {
	return TableNameBaExamplesTableCellPre
}
