// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableHeaderBtn = "ba_examples_table_header_btn"

// BaExamplesTableHeaderBtn 自定义表头按钮
type BaExamplesTableHeaderBtn struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String     string `gorm:"column:string;not null;comment:字符串" json:"string"`             // 字符串
	Number     int32  `gorm:"column:number;not null;comment:数字" json:"number"`              // 数字
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableHeaderBtn's table name
func (*BaExamplesTableHeaderBtn) TableName() string {
	return TableNameBaExamplesTableHeaderBtn
}
