// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaExamplesTableFixed = "ba_examples_table_fixed"

// BaExamplesTableFixed 固定列固定表头
type BaExamplesTableFixed struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	String1    string `gorm:"column:string1;not null;comment:字符串1" json:"string1"`          // 字符串1
	String2    string `gorm:"column:string2;not null;comment:字符串2" json:"string2"`          // 字符串2
	String3    string `gorm:"column:string3;not null;comment:字符串3" json:"string3"`          // 字符串3
	String4    string `gorm:"column:string4;not null;comment:字符串4" json:"string4"`          // 字符串4
	String5    string `gorm:"column:string5;not null;comment:字符串5" json:"string5"`          // 字符串5
	UpdateTime int64  `gorm:"column:update_time;comment:修改时间" json:"update_time"`           // 修改时间
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableFixed's table name
func (*BaExamplesTableFixed) TableName() string {
	return TableNameBaExamplesTableFixed
}
