// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaExamplesTableExpand = "ba_examples_table_expand"

// BaExamplesTableExpand 展开行
type BaExamplesTableExpand struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID     int32     `gorm:"column:user_id;not null;comment:会员ID" json:"user_id"`          // 会员ID
	Date       time.Time `gorm:"column:date;comment:日期" json:"date"`                           // 日期
	Address    string    `gorm:"column:address;not null;comment:详细地址" json:"address"`          // 详细地址
	Code       string    `gorm:"column:code;not null;comment:邮编" json:"code"`                  // 邮编
	CreateTime int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName BaExamplesTableExpand's table name
func (*BaExamplesTableExpand) TableName() string {
	return TableNameBaExamplesTableExpand
}
