// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaReply = "ba_reply"

// BaReply 系统话术库
type BaReply struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Content string `gorm:"column:content;not null;comment:话术" json:"content"`            // 话术
	Weigh   int32  `gorm:"column:weigh;comment:权重" json:"weigh"`                         // 权重
}

// TableName BaReply's table name
func (*BaReply) TableName() string {
	return TableNameBaReply
}
