// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBaService = "ba_service"

// BaService 专员轮询表
type BaService struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`              // ID
	AdminID         int32     `gorm:"column:admin_id;not null;comment:专员" json:"admin_id"`                       // 专员
	More            int32     `gorm:"column:more;not null;comment:可多接" json:"more"`                              // 可多接
	Recive          int32     `gorm:"column:recive;not null;comment:已接粉" json:"recive"`                          // 已接粉
	AverReceiveTime int32     `gorm:"column:aver_receive_time;not null;comment:平均接待时长" json:"aver_receive_time"` // 平均接待时长
	Conversion      int32     `gorm:"column:conversion;not null;comment:转化数" json:"conversion"`                  // 转化数
	Status          bool      `gorm:"column:status;not null;default:1;comment:状态:0=禁用,1=启用" json:"status"`       // 状态:0=禁用,1=启用
	Date            time.Time `gorm:"column:date;comment:日期" json:"date"`                                        // 日期
	CreateTime      int64     `gorm:"column:create_time;comment:创建时间" json:"create_time"`                        // 创建时间
}

// TableName BaService's table name
func (*BaService) TableName() string {
	return TableNameBaService
}
