// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaTeam = "ba_team"

// BaTeam 团队
type BaTeam struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name    string `gorm:"column:name;not null;comment:团队名称" json:"name"`                // 团队名称
	AdminID int32  `gorm:"column:admin_id;not null;comment:负责人" json:"admin_id"`         // 负责人
}

// TableName BaTeam's table name
func (*BaTeam) TableName() string {
	return TableNameBaTeam
}
