// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaTree = "ba_tree"

// BaTree 树
type BaTree struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Pid  int32  `gorm:"column:pid;not null;comment:上级" json:"pid"`                    // 上级
	Name string `gorm:"column:name;not null;comment:名称" json:"name"`                  // 名称
}

// TableName BaTree's table name
func (*BaTree) TableName() string {
	return TableNameBaTree
}
