package handler

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewAdminGroupHandler,
	NewAdminGroupRegistrar,
	NewAdminInfoRegistrar,
	NewAdminLogRegistrar,
	NewAdminRegistrar,
	NewAdminInfoHandler,
	NewAdminLogHandler,
	NewAdminRuleHandler,
	NewAdminRuleRegistrar,
	NewAdminHandler,
	NewAjaxHandler,
	NewAttachmentHandler,
	NewAttachmentRegistrar,
	NewConfigHandler,
	NewConfigRegistrar,
	NewCrudLogHandler,
	NewCrudLogRegistrar,
	NewCrudHandler,
	NewCrudRegistrar,
	NewDashboardHandler,
	NewDashboardRegistrar,
	NewDataRecycleLogHandler,
	NewDataRecycleLogRegistrar,
	NewDataRecycleHandler,
	NewDataRecycleRegistrar,
	NewIndexHandler,
	NewSensitiveDataLogHandler,
	NewSensitiveDataLogRegistrar,
	NewSensitiveDataHandler,
	NewSensitiveDataRegistrar,
	NewTestBuildHandler,
	NewTestBuildRegistrar,
	NewUserGroupHandlerWithAuth,
	NewUserGroupRegistrar,
	NewUserMoneyLogHandler,
	NewUserRuleHandlerWithAuth,
	NewUserRuleRegistrar,
	NewUserScoreLogHandler,
	NewUserLogRegistrar,
	NewUserHandlerWithAuth,
	NewUserRegistrar,
	NewModuleHandler,
	NewModuleRegistrar,

	NewCountryLanguageHandler,
	NewCountryLanguageRegistrar,

	NewCountryCurrencyHandler,
	NewCountryCurrencyRegistrar,
	NewCountryLanguageContentHandler,
	NewCountryLanguageContentRegistrar,
)
