// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"buildadmin-go/internal/admin/handler"
	"buildadmin-go/internal/admin/middleware"
	"buildadmin-go/internal/admin/repository"
	"buildadmin-go/internal/admin/router"
	handler2 "buildadmin-go/internal/api/handler"
	middleware2 "buildadmin-go/internal/api/middleware"
	router2 "buildadmin-go/internal/api/router"
	"buildadmin-go/internal/api/service/member"
	"buildadmin-go/internal/cmd"
	handler3 "buildadmin-go/internal/cmd/handler"
	"buildadmin-go/internal/common/area"
	"buildadmin-go/internal/common/country"
	"buildadmin-go/internal/common/money"
	"buildadmin-go/internal/common/siteconfig"
	"buildadmin-go/internal/common/upload"
	"buildadmin-go/internal/conf"
	"buildadmin-go/internal/cron"
	"buildadmin-go/internal/infra/db"
	"buildadmin-go/internal/infra/rds"
	"buildadmin-go/internal/model"
	"buildadmin-go/internal/pkg/captcha"
	"buildadmin-go/internal/pkg/clickcaptcha"
	"buildadmin-go/internal/pkg/data_scope"
	"buildadmin-go/internal/pkg/terminal"
	"buildadmin-go/internal/pkg/token"
	router3 "buildadmin-go/internal/router"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	gormDB := db.NewDB(configuration, zapLogger)
	client := rds.NewRedis(configuration, zapLogger)
	tokenHelper := token.NewTokenHelper(configuration, zapLogger, gormDB, client)
	authRepository := repository.NewAuthRepository(gormDB, tokenHelper, configuration)
	authorization := middleware.NewAuthorization(authRepository, zapLogger)
	login := middleware.NewLogin(configuration, tokenHelper, authRepository)
	closureEnforcer := data_scope.NewClosureEnforcer(configuration)
	security := middleware.NewSecurity(configuration, zapLogger, gormDB, closureEnforcer)
	adminLogRepository := repository.NewAdminLogRepository(gormDB, configuration, authRepository)
	record := middleware.NewRecord(configuration, adminLogRepository)
	service := siteconfig.NewService(gormDB)
	configRepository := repository.NewConfigRepository(gormDB, configuration, service)
	countryService := country.NewService(gormDB, configuration)
	clickCaptcha := clickcaptcha.NewClickCaptcha(configuration, gormDB)
	indexHandler := handler.NewIndexHandler(configuration, zapLogger, authRepository, configRepository, countryService, clickCaptcha)
	areaModel := area.NewAreaModel(gormDB, configuration)
	tableRepository := repository.NewTableRepository(configuration, gormDB)
	aliossStorage := upload.NewAliossStorage(gormDB, configuration)
	uploadHelper := upload.NewUploadHelper(gormDB, configuration, aliossStorage)
	terminalTerminal := terminal.NewTerminal(configuration, zapLogger, authRepository)
	ajaxHandler := handler.NewAjaxHandler(zapLogger, areaModel, tableRepository, uploadHelper, terminalTerminal, configuration)
	logModel := model.NewLogModel(gormDB, configuration, closureEnforcer)
	logHandler := handler.NewLogHandler(zapLogger, logModel, authRepository)
	moduleHandler := handler.NewModuleHandler(zapLogger)
	adminGroupRepository := repository.NewAdminGroupRepository(gormDB, configuration)
	adminRuleRepository := repository.NewAdminRuleRepository(gormDB, configuration)
	adminGroupHandler := handler.NewAdminGroupHandler(zapLogger, adminGroupRepository, adminRuleRepository, authRepository)
	adminRuleHandler := handler.NewAdminRuleHandler(zapLogger, adminRuleRepository, authRepository)
	configHandler := handler.NewConfigHandler(zapLogger, configuration, configRepository)
	attachmentRepository := repository.NewAttachmentRepository(gormDB, configuration, closureEnforcer)
	attachmentHandler := handler.NewAttachmentHandler(zapLogger, attachmentRepository)
	adminRepository := repository.NewAdminRepository(gormDB, configuration)
	adminHandler := handler.NewAdminHandler(zapLogger, adminRepository, authRepository)
	userRepository := repository.NewUserRepository(gormDB, configuration, closureEnforcer)
	userHandler := handler.NewUserHandler(zapLogger, userRepository)
	dataRecycleRepository := repository.NewDataRecycleRepository(gormDB, configuration)
	dataRecycleHandler := handler.NewDataRecycleHandler(zapLogger, configuration, dataRecycleRepository, tableRepository)
	dataRecycleLogRepository := repository.NewDataRecycleLogRepository(gormDB, configuration)
	dataRecycleLogHandler := handler.NewDataRecycleLogHandler(zapLogger, configuration, dataRecycleLogRepository)
	sensitiveDataRepository := repository.NewSensitiveDataRepository(gormDB, configuration)
	sensitiveDataHandler := handler.NewSensitiveDataHandler(zapLogger, configuration, sensitiveDataRepository, tableRepository)
	sensitiveDataLogRepository := repository.NewSensitiveDataLogRepository(gormDB, configuration)
	sensitiveDataLogHandler := handler.NewSensitiveDataLogHandler(zapLogger, configuration, sensitiveDataLogRepository)
	adminInfoHandler := handler.NewAdminInfoHandler(zapLogger, adminRepository, authRepository)
	adminLogHandler := handler.NewAdminLogHandler(zapLogger, adminLogRepository)
	crudHandler := handler.NewCrudHandler(zapLogger, tableRepository, logModel, adminRuleRepository, configuration)
	dashboardHandler := handler.NewDashboardHandler(zapLogger, adminRuleRepository)
	balanceService := money.NewBalanceService()
	moneyLogRepository := repository.NewMoneyLogRepository(gormDB, configuration, closureEnforcer, balanceService)
	moneyLogHandler := handler.NewMoneyLogHandler(zapLogger, moneyLogRepository)
	currencyRepository := repository.NewCurrencyRepository(gormDB, configuration, closureEnforcer)
	currencyHandler := handler.NewCurrencyHandler(zapLogger, currencyRepository)
	languageRepository := repository.NewLanguageRepository(gormDB, configuration, closureEnforcer)
	languageHandler := handler.NewLanguageHandler(zapLogger, languageRepository)
	languageContentRepository := repository.NewLanguageContentRepository(gormDB, configuration, closureEnforcer)
	languageContentHandler := handler.NewLanguageContentHandler(zapLogger, languageContentRepository)
	v := router.ProvideRegistrars(logHandler, moduleHandler, adminGroupHandler, adminRuleHandler, configHandler, attachmentHandler, adminHandler, userHandler, dataRecycleHandler, dataRecycleLogHandler, sensitiveDataHandler, sensitiveDataLogHandler, adminInfoHandler, adminLogHandler, crudHandler, dashboardHandler, moneyLogHandler, currencyHandler, languageHandler, languageContentHandler)
	adminRouterDeps := router.AdminRouterDeps{
		LoginM:         login,
		AuthorizationM: authorization,
		SecurityM:      security,
		RecordM:        record,
		IndexHandler:   indexHandler,
		AjaxHandler:    ajaxHandler,
		Registrars:     v,
	}
	adminRouter := router.NewAdminRouter(adminRouterDeps)
	memberService := member.NewService(gormDB, tokenHelper, configuration)
	userLogin := middleware2.NewUserLogin(configuration, tokenHelper, memberService)
	installHandler := handler2.NewInstallHandler(zapLogger, configuration, terminalTerminal)
	captchaService := captcha.NewCaptchaService(gormDB)
	commonHandler := handler2.NewCommonHandler(zapLogger, clickCaptcha, captchaService, tokenHelper, memberService, configuration)
	handlerUserHandler := handler2.NewUserHandler(zapLogger, configuration, memberService, clickCaptcha)
	v2 := router2.ProvideRegistrars(commonHandler, handlerUserHandler)
	apiRouterDeps := router2.ApiRouterDeps{
		UserLoginM:     userLogin,
		InstallHandler: installHandler,
		Registrars:     v2,
	}
	apiRouter := router2.NewApiRouter(apiRouterDeps)
	engine := router3.InitRouter(lumberjackLogger, adminRouter, apiRouter)
	server := newHttpServer(configuration, engine)
	exampleJob := cron.NewExampleJob(zapLogger)
	cronCron := cron.NewCron(gormDB, zapLogger, exampleJob)
	app := newApp(configuration, zapLogger, authorization, server, cronCron)
	return app, func() {
	}, nil
}

// wireCommand init application.
func wireCommand(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*cmd.Command, func(), error) {
	exampleHandler := handler3.NewExampleHandler(zapLogger)
	migrateHandler := handler3.NewMigrateHandler(zapLogger, configuration)
	crudHandler := handler3.NewCrudHandler(zapLogger, configuration)
	command := cmd.NewCommand(exampleHandler, migrateHandler, crudHandler)
	return command, func() {
	}, nil
}
