// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"buildadmin-go/internal/admin/handler"
	"buildadmin-go/internal/admin/middleware"
	"buildadmin-go/internal/admin/repository"
	"buildadmin-go/internal/admin/router"
	"buildadmin-go/internal/admin/service"
	handler2 "buildadmin-go/internal/api/handler"
	middleware2 "buildadmin-go/internal/api/middleware"
	router2 "buildadmin-go/internal/api/router"
	service2 "buildadmin-go/internal/api/service"
	"buildadmin-go/internal/commands"
	"buildadmin-go/internal/common/area"
	"buildadmin-go/internal/common/country"
	"buildadmin-go/internal/common/money"
	"buildadmin-go/internal/common/siteconfig"
	"buildadmin-go/internal/common/upload"
	"buildadmin-go/internal/conf"
	"buildadmin-go/internal/cron"
	"buildadmin-go/internal/infra/db"
	"buildadmin-go/internal/infra/rds"
	"buildadmin-go/internal/model"
	"buildadmin-go/internal/pkg/captcha"
	"buildadmin-go/internal/pkg/clickcaptcha"
	"buildadmin-go/internal/pkg/data_scope"
	"buildadmin-go/internal/pkg/terminal"
	"buildadmin-go/internal/pkg/token"
	router3 "buildadmin-go/internal/router"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *conf.Configuration, logger *lumberjack.Logger, zapLogger *zap.Logger) (*commands.ServerApp, func(), error) {
	gormDB := db.NewDB(configuration, zapLogger)
	client := rds.NewRedis(configuration, zapLogger)
	tokenHelper := token.NewTokenHelper(configuration, zapLogger, gormDB, client)
	authRepository := repository.NewAuthRepository(gormDB, tokenHelper, configuration)
	authorization := middleware.NewAuthorization(authRepository, zapLogger)
	login := middleware.NewLogin(configuration, tokenHelper, authRepository)
	closureEnforcer := data_scope.NewClosureEnforcer(configuration)
	security := middleware.NewSecurity(configuration, zapLogger, gormDB, closureEnforcer)
	adminLogRepository := repository.NewAdminLogRepository(gormDB, configuration, authRepository)
	record := middleware.NewRecord(configuration, adminLogRepository)
	siteconfigService := siteconfig.NewService(gormDB)
	configRepository := repository.NewConfigRepository(gormDB, configuration, siteconfigService)
	countryService := country.NewService(gormDB, configuration)
	clickCaptcha := clickcaptcha.NewClickCaptcha(configuration, gormDB)
	authService := service.NewAuthService(configuration, authRepository, clickCaptcha, tokenHelper)
	indexHandler := handler.NewIndexHandler(configuration, zapLogger, authRepository, configRepository, countryService, authService)
	areaModel := area.NewAreaModel(gormDB, configuration)
	tableRepository := repository.NewTableRepository(configuration, gormDB)
	aliossStorage := upload.NewAliossStorage(gormDB, configuration)
	uploadHelper := upload.NewUploadHelper(gormDB, configuration, aliossStorage)
	terminalTerminal := terminal.NewTerminal(configuration, zapLogger, authRepository)
	ajaxHandler := handler.NewAjaxHandler(zapLogger, areaModel, tableRepository, uploadHelper, terminalTerminal, configuration)
	logModel := model.NewLogModel(gormDB, configuration, closureEnforcer)
	logHandler := handler.NewLogHandler(zapLogger, logModel, authRepository)
	moduleHandler := handler.NewModuleHandler(zapLogger)
	adminGroupRepository := repository.NewAdminGroupRepository(gormDB, configuration)
	adminRuleRepository := repository.NewAdminRuleRepository(gormDB, configuration)
	adminGroupService := service.NewAdminGroupService(adminGroupRepository, adminRuleRepository, authRepository)
	adminGroupHandler := handler.NewAdminGroupHandler(zapLogger, adminGroupRepository, adminRuleRepository, authRepository, adminGroupService)
	adminRuleService := service.NewAdminRuleService(adminRuleRepository)
	adminRuleHandler := handler.NewAdminRuleHandler(zapLogger, adminRuleRepository, authRepository, adminRuleService)
	configService := service.NewConfigService(configRepository)
	configHandler := handler.NewConfigHandler(zapLogger, configuration, configRepository, configService)
	attachmentRepository := repository.NewAttachmentRepository(gormDB, configuration, closureEnforcer)
	routineAttachmentService := service.NewRoutineAttachmentService(attachmentRepository, configuration)
	attachmentHandler := handler.NewAttachmentHandler(zapLogger, attachmentRepository, routineAttachmentService)
	adminRepository := repository.NewAdminRepository(gormDB, configuration)
	adminService := service.NewAdminService(adminRepository, authRepository, configuration)
	adminHandler := handler.NewAdminHandler(zapLogger, adminRepository, authRepository, adminService)
	userRepository := repository.NewUserRepository(gormDB, configuration, closureEnforcer)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(zapLogger, userRepository, userService)
	securityDataRecycleRepository := repository.NewSecurityDataRecycleRepository(gormDB, configuration)
	securityDataRecycleService := service.NewSecurityDataRecycleService(securityDataRecycleRepository)
	dataRecycleHandler := handler.NewDataRecycleHandler(zapLogger, configuration, securityDataRecycleRepository, tableRepository, securityDataRecycleService)
	securityDataRecycleLogRepository := repository.NewSecurityDataRecycleLogRepository(gormDB, configuration)
	securityDataRecycleLogService := service.NewSecurityDataRecycleLogService(securityDataRecycleLogRepository)
	dataRecycleLogHandler := handler.NewDataRecycleLogHandler(zapLogger, configuration, securityDataRecycleLogRepository, securityDataRecycleLogService)
	securitySensitiveDataRepository := repository.NewSecuritySensitiveDataRepository(gormDB, configuration)
	sensitiveDataService := service.NewSensitiveDataService(securitySensitiveDataRepository)
	sensitiveDataHandler := handler.NewSensitiveDataHandler(zapLogger, configuration, securitySensitiveDataRepository, tableRepository, sensitiveDataService)
	securitySensitiveDataLogRepository := repository.NewSecuritySensitiveDataLogRepository(gormDB, configuration)
	securitySensitiveDataLogService := service.NewSecuritySensitiveDataLogService(securitySensitiveDataLogRepository)
	sensitiveDataLogHandler := handler.NewSensitiveDataLogHandler(zapLogger, configuration, securitySensitiveDataLogRepository, securitySensitiveDataLogService)
	adminInfoHandler := handler.NewAdminInfoHandler(zapLogger, adminRepository, authRepository)
	adminLogHandler := handler.NewAdminLogHandler(zapLogger, adminLogRepository)
	crudHandler := handler.NewCrudHandler(zapLogger, tableRepository, logModel, adminRuleRepository, configuration)
	dashboardHandler := handler.NewDashboardHandler(zapLogger, adminRuleRepository)
	userMoneyLogRepository := repository.NewUserMoneyLogRepository(gormDB, configuration, closureEnforcer)
	userBalanceService := money.NewUserBalanceService()
	userMoneyLogService := service.NewUserMoneyLogService(userMoneyLogRepository, userBalanceService)
	moneyLogHandler := handler.NewMoneyLogHandler(zapLogger, userMoneyLogRepository, userMoneyLogService)
	countryCurrencyRepository := repository.NewCountryCurrencyRepository(gormDB, configuration, closureEnforcer)
	countryCurrencyHandler := handler.NewCountryCurrencyHandler(zapLogger, countryCurrencyRepository)
	countryLanguageRepository := repository.NewCountryLanguageRepository(gormDB, configuration, closureEnforcer)
	countryLanguageHandler := handler.NewCountryLanguageHandler(zapLogger, countryLanguageRepository)
	countryLanguageContentRepository := repository.NewCountryLanguageContentRepository(gormDB, configuration, closureEnforcer)
	countryLanguageContentHandler := handler.NewCountryLanguageContentHandler(zapLogger, countryLanguageContentRepository)
	v := router.ProvideRegistrars(logHandler, moduleHandler, adminGroupHandler, adminRuleHandler, configHandler, attachmentHandler, adminHandler, userHandler, dataRecycleHandler, dataRecycleLogHandler, sensitiveDataHandler, sensitiveDataLogHandler, adminInfoHandler, adminLogHandler, crudHandler, dashboardHandler, moneyLogHandler, countryCurrencyHandler, countryLanguageHandler, countryLanguageContentHandler)
	adminRouterDeps := router.AdminRouterDeps{
		LoginM:         login,
		AuthorizationM: authorization,
		SecurityM:      security,
		RecordM:        record,
		IndexHandler:   indexHandler,
		AjaxHandler:    ajaxHandler,
		Registrars:     v,
	}
	adminRouter := router.NewAdminRouter(adminRouterDeps)
	memberService := service2.NewMemberService(gormDB, tokenHelper, configuration)
	userLogin := middleware2.NewUserLogin(configuration, tokenHelper, memberService)
	captchaService := captcha.NewCaptchaService(gormDB)
	commonHandler := handler2.NewCommonHandler(zapLogger, clickCaptcha, captchaService, tokenHelper, memberService, configuration, uploadHelper)
	handlerUserHandler := handler2.NewUserHandler(zapLogger, configuration, memberService, clickCaptcha)
	v2 := router2.ProvideRegistrars(commonHandler, handlerUserHandler)
	apiRouterDeps := router2.ApiRouterDeps{
		UserLoginM: userLogin,
		Registrars: v2,
	}
	apiRouter := router2.NewApiRouter(apiRouterDeps)
	engine := router3.InitRouter(logger, adminRouter, apiRouter)
	server := commands.NewHttpServer(configuration, engine)
	exampleJob := cron.NewExampleJob(zapLogger)
	cronCron := cron.NewCron(gormDB, zapLogger, exampleJob)
	serverApp := commands.NewServerApp(configuration, zapLogger, authorization, server, cronCron)
	return serverApp, func() {
	}, nil
}

// wireCommand init application.
func wireCommand(configuration *conf.Configuration, logger *lumberjack.Logger, zapLogger *zap.Logger) (*commands.Command, func(), error) {
	exampleHandler := commands.NewExampleHandler(zapLogger)
	migrateHandler := commands.NewMigrateHandler(zapLogger, configuration)
	crudHandler := commands.NewCrudHandler(zapLogger, configuration)
	command := commands.NewCommand(exampleHandler, migrateHandler, crudHandler)
	return command, func() {
	}, nil
}
