// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"buildadmin-go/internal/admin/handler"
	auth2 "buildadmin-go/internal/admin/handler/auth"
	country3 "buildadmin-go/internal/admin/handler/country"
	crud2 "buildadmin-go/internal/admin/handler/crud"
	routine2 "buildadmin-go/internal/admin/handler/routine"
	security2 "buildadmin-go/internal/admin/handler/security"
	user2 "buildadmin-go/internal/admin/handler/user"
	"buildadmin-go/internal/admin/middleware"
	"buildadmin-go/internal/admin/model/crud"
	"buildadmin-go/internal/admin/repository"
	"buildadmin-go/internal/admin/repository/auth"
	country2 "buildadmin-go/internal/admin/repository/country"
	"buildadmin-go/internal/admin/repository/routine"
	"buildadmin-go/internal/admin/repository/security"
	"buildadmin-go/internal/admin/repository/user"
	"buildadmin-go/internal/admin/router"
	handler2 "buildadmin-go/internal/api/handler"
	middleware2 "buildadmin-go/internal/api/middleware"
	router2 "buildadmin-go/internal/api/router"
	"buildadmin-go/internal/api/service/member"
	"buildadmin-go/internal/cmd"
	handler3 "buildadmin-go/internal/cmd/handler"
	"buildadmin-go/internal/common/area"
	"buildadmin-go/internal/common/country"
	"buildadmin-go/internal/common/money"
	"buildadmin-go/internal/common/siteconfig"
	"buildadmin-go/internal/common/upload"
	"buildadmin-go/internal/conf"
	"buildadmin-go/internal/cron"
	"buildadmin-go/internal/infra/db"
	"buildadmin-go/internal/infra/rds"
	"buildadmin-go/internal/pkg/captcha"
	"buildadmin-go/internal/pkg/clickcaptcha"
	"buildadmin-go/internal/pkg/data_scope"
	"buildadmin-go/internal/pkg/terminal"
	"buildadmin-go/internal/pkg/token"
	router3 "buildadmin-go/internal/router"
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	gormDB := db.NewDB(configuration, zapLogger)
	client := rds.NewRedis(configuration, zapLogger)
	tokenHelper := token.NewTokenHelper(configuration, zapLogger, gormDB, client)
	authRepository := auth.NewAuthRepository(gormDB, tokenHelper, configuration)
	authorization := middleware.NewAuthorization(authRepository, zapLogger)
	login := middleware.NewLogin(configuration, tokenHelper, authRepository)
	closureEnforcer := data_scope.NewClosureEnforcer(configuration)
	middlewareSecurity := middleware.NewSecurity(configuration, zapLogger, gormDB, closureEnforcer)
	adminLogRepository := auth.NewAdminLogRepository(gormDB, configuration, authRepository)
	record := middleware.NewRecord(configuration, adminLogRepository)
	service := siteconfig.NewService(gormDB)
	configRepository := routine.NewConfigRepository(gormDB, configuration, service)
	countryService := country.NewService(gormDB, configuration)
	clickCaptcha := clickcaptcha.NewClickCaptcha(configuration, gormDB)
	indexHandler := handler.NewIndexHandler(configuration, zapLogger, authRepository, configRepository, countryService, clickCaptcha)
	areaModel := area.NewAreaModel(gormDB, configuration)
	tableRepository := repository.NewTableRepository(configuration, gormDB)
	aliossStorage := upload.NewAliossStorage(gormDB, configuration)
	uploadHelper := upload.NewUploadHelper(gormDB, configuration, aliossStorage)
	terminalTerminal := terminal.NewTerminal(configuration, zapLogger, authRepository)
	ajaxHandler := handler.NewAjaxHandler(zapLogger, areaModel, tableRepository, uploadHelper, terminalTerminal, configuration)
	adminRouterDeps := router.AdminRouterDeps{
		LoginM:         login,
		AuthorizationM: authorization,
		SecurityM:      middlewareSecurity,
		RecordM:        record,
		IndexHandler:   indexHandler,
		AjaxHandler:    ajaxHandler,
	}
	adminRouter := router.NewAdminRouter(adminRouterDeps)
	memberService := member.NewService(gormDB, tokenHelper, configuration)
	userLogin := middleware2.NewUserLogin(configuration, tokenHelper, memberService)
	installHandler := handler2.NewInstallHandler(zapLogger, configuration, terminalTerminal)
	apiRouterDeps := router2.ApiRouterDeps{
		UserLoginM:     userLogin,
		InstallHandler: installHandler,
	}
	apiRouter := router2.NewApiRouter(apiRouterDeps)
	logModel := crud.NewLogModel(gormDB, configuration, closureEnforcer)
	logHandler := crud2.NewLogHandler(zapLogger, logModel, authRepository)
	logRegistrar := crud2.NewLogRegistrar(logHandler)
	moduleHandler := handler.NewModuleHandler(zapLogger)
	moduleRegistrar := handler.NewModuleRegistrar(moduleHandler)
	adminGroupRepository := auth.NewAdminGroupRepository(gormDB, configuration)
	adminRuleRepository := auth.NewAdminRuleRepository(gormDB, configuration)
	adminGroupHandler := auth2.NewAdminGroupHandler(zapLogger, adminGroupRepository, adminRuleRepository, authRepository)
	adminGroupRegistrar := auth2.NewAdminGroupRegistrar(adminGroupHandler)
	adminRuleHandler := auth2.NewAdminRuleHandler(zapLogger, adminRuleRepository, authRepository)
	adminRuleRegistrar := auth2.NewAdminRuleRegistrar(adminRuleHandler)
	configHandler := routine2.NewConfigHandler(zapLogger, configuration, configRepository)
	configRegistrar := routine2.NewConfigRegistrar(configHandler)
	attachmentRepository := routine.NewAttachmentRepository(gormDB, configuration, closureEnforcer)
	attachmentHandler := routine2.NewAttachmentHandler(zapLogger, attachmentRepository)
	attachmentRegistrar := routine2.NewAttachmentRegistrar(attachmentHandler)
	adminRepository := auth.NewAdminRepository(gormDB, configuration)
	adminHandler := auth2.NewAdminHandler(zapLogger, adminRepository, authRepository)
	adminRegistrar := auth2.NewAdminRegistrar(adminHandler)
	userRepository := user.NewUserRepository(gormDB, configuration, closureEnforcer)
	userHandler := user2.NewUserHandler(zapLogger, userRepository)
	userRegistrar := user2.NewUserRegistrar(userHandler)
	dataRecycleRepository := security.NewDataRecycleRepository(gormDB, configuration)
	dataRecycleHandler := security2.NewDataRecycleHandler(zapLogger, configuration, dataRecycleRepository, tableRepository)
	dataRecycleRegistrar := security2.NewDataRecycleRegistrar(dataRecycleHandler)
	dataRecycleLogRepository := security.NewDataRecycleLogRepository(gormDB, configuration)
	dataRecycleLogHandler := security2.NewDataRecycleLogHandler(zapLogger, configuration, dataRecycleLogRepository)
	dataRecycleLogRegistrar := security2.NewDataRecycleLogRegistrar(dataRecycleLogHandler)
	sensitiveDataRepository := security.NewSensitiveDataRepository(gormDB, configuration)
	sensitiveDataHandler := security2.NewSensitiveDataHandler(zapLogger, configuration, sensitiveDataRepository, tableRepository)
	sensitiveDataRegistrar := security2.NewSensitiveDataRegistrar(sensitiveDataHandler)
	sensitiveDataLogRepository := security.NewSensitiveDataLogRepository(gormDB, configuration)
	sensitiveDataLogHandler := security2.NewSensitiveDataLogHandler(zapLogger, configuration, sensitiveDataLogRepository)
	sensitiveDataLogRegistrar := security2.NewSensitiveDataLogRegistrar(sensitiveDataLogHandler)
	adminInfoHandler := routine2.NewAdminInfoHandler(zapLogger, adminRepository, authRepository)
	adminInfoRegistrar := routine2.NewAdminInfoRegistrar(adminInfoHandler)
	adminLogHandler := auth2.NewAdminLogHandler(zapLogger, adminLogRepository)
	adminLogRegistrar := auth2.NewAdminLogRegistrar(adminLogHandler)
	crudHandler := crud2.NewCrudHandler(zapLogger, tableRepository, logModel, adminRuleRepository, configuration)
	crudRegistrar := crud2.NewCrudRegistrar(crudHandler)
	dashboardHandler := handler.NewDashboardHandler(zapLogger, adminRuleRepository)
	dashboardRegistrar := handler.NewDashboardRegistrar(dashboardHandler)
	balanceService := money.NewBalanceService()
	moneyLogRepository := user.NewMoneyLogRepository(gormDB, configuration, closureEnforcer, balanceService)
	moneyLogHandler := user2.NewMoneyLogHandler(zapLogger, moneyLogRepository)
	userLogRegistrar := user2.NewUserLogRegistrar(userHandler, moneyLogHandler)
	captchaService := captcha.NewCaptchaService(gormDB)
	commonHandler := handler2.NewCommonHandler(zapLogger, clickCaptcha, captchaService, tokenHelper, memberService, configuration)
	commonRegistrar := handler2.NewCommonRegistrar(commonHandler)
	handlerUserHandler := handler2.NewUserHandler(zapLogger, configuration, memberService, clickCaptcha)
	handlerUserRegistrar := handler2.NewUserRegistrar(handlerUserHandler)
	currencyRepository := country2.NewCurrencyRepository(gormDB, configuration, closureEnforcer)
	currencyHandler := country3.NewCurrencyHandler(zapLogger, currencyRepository)
	currencyRegistrar := country3.NewCurrencyRegistrar(currencyHandler)
	languageRepository := country2.NewLanguageRepository(gormDB, configuration, closureEnforcer)
	languageHandler := country3.NewLanguageHandler(zapLogger, languageRepository)
	languageRegistrar := country3.NewLanguageRegistrar(languageHandler)
	languageContentRepository := country2.NewLanguageContentRepository(gormDB, configuration, closureEnforcer)
	languageContentHandler := country3.NewLanguageContentHandler(zapLogger, languageContentRepository)
	languageContentRegistrar := country3.NewLanguageContentRegistrar(languageContentHandler)
	v := router3.ProvideRegistrars(logRegistrar, moduleRegistrar, adminGroupRegistrar, adminRuleRegistrar, configRegistrar, attachmentRegistrar, adminRegistrar, userRegistrar, dataRecycleRegistrar, dataRecycleLogRegistrar, sensitiveDataRegistrar, sensitiveDataLogRegistrar, adminInfoRegistrar, adminLogRegistrar, crudRegistrar, dashboardRegistrar, userLogRegistrar, commonRegistrar, handlerUserRegistrar, currencyRegistrar, languageRegistrar, languageContentRegistrar)
	engine := router3.InitRouter(lumberjackLogger, adminRouter, apiRouter, v)
	server := newHttpServer(configuration, engine)
	exampleJob := cron.NewExampleJob(zapLogger)
	cronCron := cron.NewCron(gormDB, zapLogger, exampleJob)
	app := newApp(configuration, zapLogger, authorization, server, cronCron)
	return app, func() {
	}, nil
}

// wireCommand init application.
func wireCommand(configuration *conf.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*cmd.Command, func(), error) {
	exampleHandler := handler3.NewExampleHandler(zapLogger)
	migrateHandler := handler3.NewMigrateHandler(zapLogger, configuration)
	crudHandler := handler3.NewCrudHandler(zapLogger, configuration)
	command := cmd.NewCommand(exampleHandler, migrateHandler, crudHandler)
	return command, func() {
	}, nil
}
